# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class IntegrationTelegramAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :confidential_issues_events, T::Bool
    attribute :confidential_note_events, T::Bool
    attribute :issues_events, T::Bool
    attribute :merge_requests_events, T::Bool
    attribute :note_events, T::Bool
    attribute :pipeline_events, T::Bool
    attribute :project, T::String
    attribute :push_events, T::Bool
    attribute :room, T::String
    attribute :tag_push_events, T::Bool
    attribute :token, T::String
    attribute :wiki_page_events, T::Bool
  end
end
