# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_project_membership/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabProjectMembership
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_project_membership,
      attributes_class: Gitlab::Types::ProjectMembershipAttributes,
      outputs: { id: :id },
      map: [:access_level, :project, :user_id],
      map_present: [:expires_at, :member_role_id]
  end
  module Gitlab
    include GitlabProjectMembership
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
