# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class ProjectMembershipAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :access_level, T::String
    attribute :project, T::String
    attribute :user_id, T::Float
    attribute? :expires_at, T::String.optional
    attribute? :member_role_id, T::Float.optional
  end
end
