# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_personal_access_token/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabPersonalAccessToken
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_personal_access_token,
      attributes_class: Gitlab::Types::PersonalAccessTokenAttributes,
      outputs: { id: :id },
      map: [:name, :scopes, :user_id],
      map_present: [:rotation_configuration]
  end
  module Gitlab
    include GitlabPersonalAccessToken
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
