# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_runner/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabRunner
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_runner,
      attributes_class: Gitlab::Types::RunnerAttributes,
      outputs: { id: :id },
      map: [:registration_token],
      map_present: [:description, :maintenance_note, :maximum_timeout, :tag_list]
  end
  module Gitlab
    include GitlabRunner
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
