# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class RunnerAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :registration_token, T::String
    attribute? :description, T::String.optional
    attribute? :maintenance_note, T::String.optional
    attribute? :maximum_timeout, T::Float.optional
    attribute? :tag_list, T::Array.of(T::String).optional
  end
end
