# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_project_hook/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabProjectHook
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_project_hook,
      attributes_class: Gitlab::Types::ProjectHookAttributes,
      outputs: { id: :id },
      map: [:project, :url],
      map_present: [:custom_headers]
  end
  module Gitlab
    include GitlabProjectHook
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
