# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_cluster_agent_token/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabClusterAgentToken
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_cluster_agent_token,
      attributes_class: Gitlab::Types::ClusterAgentTokenAttributes,
      outputs: { id: :id },
      map: [:agent_id, :name, :project],
      map_present: [:description]
  end
  module Gitlab
    include GitlabClusterAgentToken
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
