# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_integration_microsoft_teams/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabIntegrationMicrosoftTeams
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_integration_microsoft_teams,
      attributes_class: Gitlab::Types::IntegrationMicrosoftTeamsAttributes,
      outputs: { id: :id },
      map: [:project, :webhook],
      map_present: [:branches_to_be_notified],
      map_bool: [:confidential_issues_events, :confidential_note_events, :issues_events, :merge_requests_events, :note_events, :notify_only_broken_pipelines, :pipeline_events, :push_events, :tag_push_events, :wiki_page_events]
  end
  module Gitlab
    include GitlabIntegrationMicrosoftTeams
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
