# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class IntegrationMicrosoftTeamsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :project, T::String
    attribute :webhook, T::String
    attribute? :branches_to_be_notified, T::String.optional
    attribute? :confidential_issues_events, T::Bool.optional
    attribute? :confidential_note_events, T::Bool.optional
    attribute? :issues_events, T::Bool.optional
    attribute? :merge_requests_events, T::Bool.optional
    attribute? :note_events, T::Bool.optional
    attribute? :notify_only_broken_pipelines, T::Bool.optional
    attribute? :pipeline_events, T::Bool.optional
    attribute? :push_events, T::Bool.optional
    attribute? :tag_push_events, T::Bool.optional
    attribute? :wiki_page_events, T::Bool.optional
  end
end
