# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_group_access_token/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabGroupAccessToken
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_group_access_token,
      attributes_class: Gitlab::Types::GroupAccessTokenAttributes,
      outputs: { id: :id },
      map: [:group, :name, :scopes],
      map_present: [:rotation_configuration]
  end
  module Gitlab
    include GitlabGroupAccessToken
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
