# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_integration_jira/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabIntegrationJira
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_integration_jira,
      attributes_class: Gitlab::Types::IntegrationJiraAttributes,
      outputs: { id: :id },
      map: [:password, :project, :url],
      map_present: [:jira_auth_type, :jira_issue_prefix, :jira_issue_regex, :jira_issue_transition_id, :project_key, :project_keys, :username],
      map_bool: [:issues_enabled, :jira_issue_transition_automatic, :use_inherited_settings]
  end
  module Gitlab
    include GitlabIntegrationJira
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
