# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_deploy_key/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabDeployKey
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_deploy_key,
      attributes_class: Gitlab::Types::DeployKeyAttributes,
      outputs: { id: :id },
      map: [:key, :project, :title],
      map_bool: [:can_push]
  end
  module Gitlab
    include GitlabDeployKey
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
