# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_integration_pipelines_email/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabIntegrationPipelinesEmail
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_integration_pipelines_email,
      attributes_class: Gitlab::Types::IntegrationPipelinesEmailAttributes,
      outputs: { id: :id },
      map: [:project, :recipients],
      map_present: [:branches_to_be_notified],
      map_bool: [:notify_only_broken_pipelines]
  end
  module Gitlab
    include GitlabIntegrationPipelinesEmail
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
