# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_project_share_group/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabProjectShareGroup
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_project_share_group,
      attributes_class: Gitlab::Types::ProjectShareGroupAttributes,
      outputs: { id: :id },
      map: [:group_id, :project],
      map_present: [:access_level, :group_access]
  end
  module Gitlab
    include GitlabProjectShareGroup
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
