# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_cluster_agent/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabClusterAgent
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_cluster_agent,
      attributes_class: Gitlab::Types::ClusterAgentAttributes,
      outputs: { id: :id },
      map: [:name, :project]
  end
  module Gitlab
    include GitlabClusterAgent
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
