# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_user_gpgkey/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabUserGpgkey
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_user_gpgkey,
      attributes_class: Gitlab::Types::UserGpgkeyAttributes,
      outputs: { id: :id },
      map: [:key],
      map_present: [:user_id]
  end
  module Gitlab
    include GitlabUserGpgkey
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
