# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_project_approval_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabProjectApprovalRule
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_project_approval_rule,
      attributes_class: Gitlab::Types::ProjectApprovalRuleAttributes,
      outputs: { id: :id },
      map: [:approvals_required, :name, :project],
      map_present: [:group_ids, :protected_branch_ids, :user_ids],
      map_bool: [:applies_to_all_protected_branches, :disable_importing_default_any_approver_rule_on_create]
  end
  module Gitlab
    include GitlabProjectApprovalRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
