# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_project_wiki_page/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabProjectWikiPage
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_project_wiki_page,
      attributes_class: Gitlab::Types::ProjectWikiPageAttributes,
      outputs: { id: :id },
      map: [:content, :project, :title]
  end
  module Gitlab
    include GitlabProjectWikiPage
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
