# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_group_custom_attribute/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabGroupCustomAttribute
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_group_custom_attribute,
      attributes_class: Gitlab::Types::GroupCustomAttributeAttributes,
      outputs: { id: :id },
      map: [:group, :key, :value]
  end
  module Gitlab
    include GitlabGroupCustomAttribute
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
