# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class ProjectFreezePeriodAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :freeze_end, T::String
    attribute :freeze_start, T::String
    attribute :project, T::String
    attribute? :cron_timezone, T::String.optional
  end
end
