# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_integration_harbor/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabIntegrationHarbor
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_integration_harbor,
      attributes_class: Gitlab::Types::IntegrationHarborAttributes,
      outputs: { id: :id },
      map: [:password, :project, :project_name, :url, :username]
  end
  module Gitlab
    include GitlabIntegrationHarbor
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
