# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class InstanceVariableAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :key, T::String
    attribute :value, T::String
    attribute? :description, T::String.optional
    attribute? :masked, T::Bool.optional
    attribute? :protected, T::Bool.optional
    attribute? :raw, T::Bool.optional
    attribute? :variable_type, T::String.optional
  end
end
