# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_project_level_notifications/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabProjectLevelNotifications
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_project_level_notifications,
      attributes_class: Gitlab::Types::ProjectLevelNotificationsAttributes,
      outputs: { id: :id },
      map: [:project]
  end
  module Gitlab
    include GitlabProjectLevelNotifications
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
