# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class BranchProtectionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :branch, T::String
    attribute :project, T::String
    attribute? :allowed_to_merge, T::Array.of(T::Hash).optional
    attribute? :allowed_to_push, T::Array.of(T::Hash).optional
    attribute? :allowed_to_unprotect, T::Array.of(T::Hash).optional
  end
end
