# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_integration_jenkins/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabIntegrationJenkins
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_integration_jenkins,
      attributes_class: Gitlab::Types::IntegrationJenkinsAttributes,
      outputs: { id: :id },
      map: [:jenkins_url, :project, :project_name],
      map_present: [:password, :username]
  end
  module Gitlab
    include GitlabIntegrationJenkins
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
