# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_user/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabUser
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_user,
      attributes_class: Gitlab::Types::UserAttributes,
      outputs: { id: :id },
      map: [:email, :name, :username],
      map_present: [:extern_uid, :external_provider, :note, :password, :projects_limit, :state],
      map_bool: [:can_create_group, :force_random_password, :is_admin, :is_external, :reset_password, :skip_confirmation]
  end
  module Gitlab
    include GitlabUser
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
