# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_user_sshkey/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabUserSshkey
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_user_sshkey,
      attributes_class: Gitlab::Types::UserSshkeyAttributes,
      outputs: { id: :id },
      map: [:key, :title],
      map_present: [:expires_at]
  end
  module Gitlab
    include GitlabUserSshkey
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
