# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_service_slack/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabServiceSlack
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_service_slack,
      attributes_class: Gitlab::Types::ServiceSlackAttributes,
      outputs: { id: :id },
      map: [:project, :webhook],
      map_present: [:confidential_issue_channel, :issue_channel, :merge_request_channel, :note_channel, :pipeline_channel, :push_channel, :tag_push_channel, :username, :wiki_page_channel]
  end
  module Gitlab
    include GitlabServiceSlack
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
