# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_project_milestone/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabProjectMilestone
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_project_milestone,
      attributes_class: Gitlab::Types::ProjectMilestoneAttributes,
      outputs: { id: :id },
      map: [:project, :title],
      map_present: [:description, :due_date, :start_date, :state]
  end
  module Gitlab
    include GitlabProjectMilestone
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
