# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class ProjectMilestoneAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :project, T::String
    attribute :title, T::String
    attribute? :description, T::String.optional
    attribute? :due_date, T::String.optional
    attribute? :start_date, T::String.optional
    attribute? :state, T::String.optional
  end
end
