# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_label/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabLabel
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_label,
      attributes_class: Gitlab::Types::LabelAttributes,
      outputs: { id: :id },
      map: [:color, :name, :project],
      map_present: [:description]
  end
  module Gitlab
    include GitlabLabel
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
