# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_group_membership/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabGroupMembership
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_group_membership,
      attributes_class: Gitlab::Types::GroupMembershipAttributes,
      outputs: { id: :id },
      map: [:access_level, :group_id, :user_id]
  end
  module Gitlab
    include GitlabGroupMembership
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
