# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_deploy_token/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabDeployToken
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_deploy_token,
      attributes_class: Gitlab::Types::DeployTokenAttributes,
      outputs: { id: :id },
      map: [:name, :scopes],
      map_present: [:expires_at, :group, :project]
  end
  module Gitlab
    include GitlabDeployToken
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
