# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class MemberRoleAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :base_access_level, T::String
    attribute :enabled_permissions, T::Array.of(T::String)
    attribute :name, T::String
  end
end
