# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class ComplianceFrameworkAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :color, T::String
    attribute :description, T::String
    attribute :name, T::String
    attribute :namespace_path, T::String
    attribute? :pipeline_configuration_full_path, T::String.optional
  end
end
