# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_project_protected_environment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabProjectProtectedEnvironment
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_project_protected_environment,
      attributes_class: Gitlab::Types::ProjectProtectedEnvironmentAttributes,
      outputs: { id: :id },
      map: [:environment, :project],
      map_present: [:deploy_access_levels]
  end
  module Gitlab
    include GitlabProjectProtectedEnvironment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
