# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_release_link/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabReleaseLink
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_release_link,
      attributes_class: Gitlab::Types::ReleaseLinkAttributes,
      outputs: { id: :id },
      map: [:name, :project, :tag_name, :url],
      map_present: [:filepath, :link_type]
  end
  module Gitlab
    include GitlabReleaseLink
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
