# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_project_tag/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabProjectTag
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_project_tag,
      attributes_class: Gitlab::Types::ProjectTagAttributes,
      outputs: { id: :id },
      map: [:name, :project, :ref],
      map_present: [:message]
  end
  module Gitlab
    include GitlabProjectTag
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
