# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_group_issue_board/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabGroupIssueBoard
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_group_issue_board,
      attributes_class: Gitlab::Types::GroupIssueBoardAttributes,
      outputs: { id: :id },
      map: [:group, :name],
      map_present: [:labels, :lists, :milestone_id]
  end
  module Gitlab
    include GitlabGroupIssueBoard
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
