# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class GroupIssueBoardAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :group, T::String
    attribute :name, T::String
    attribute? :labels, T::Array.of(T::String).optional
    attribute? :lists, T::Array.of(T::Hash).optional
    attribute? :milestone_id, T::Float.optional
  end
end
