# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_group_security_policy_attachment/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabGroupSecurityPolicyAttachment
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_group_security_policy_attachment,
      attributes_class: Gitlab::Types::GroupSecurityPolicyAttachmentAttributes,
      outputs: { id: :id },
      map: [:group, :policy_project]
  end
  module Gitlab
    include GitlabGroupSecurityPolicyAttachment
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
