# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_global_level_notifications/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabGlobalLevelNotifications
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_global_level_notifications,
      attributes_class: Gitlab::Types::GlobalLevelNotificationsAttributes,
      outputs: { id: :id }
  end
  module Gitlab
    include GitlabGlobalLevelNotifications
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
