# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_user_custom_attribute/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabUserCustomAttribute
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_user_custom_attribute,
      attributes_class: Gitlab::Types::UserCustomAttributeAttributes,
      outputs: { id: :id },
      map: [:key, :user, :value]
  end
  module Gitlab
    include GitlabUserCustomAttribute
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
