# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_group_hook/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabGroupHook
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_group_hook,
      attributes_class: Gitlab::Types::GroupHookAttributes,
      outputs: { id: :id },
      map: [:group, :url],
      map_present: [:custom_headers]
  end
  module Gitlab
    include GitlabGroupHook
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
