# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class SystemHookAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :url, T::String
    attribute? :enable_ssl_verification, T::Bool.optional
    attribute? :merge_requests_events, T::Bool.optional
    attribute? :push_events, T::Bool.optional
    attribute? :repository_update_events, T::Bool.optional
    attribute? :tag_push_events, T::Bool.optional
    attribute? :token, T::String.optional
  end
end
