# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class IntegrationEmailsOnPushAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :project, T::String
    attribute :recipients, T::String
    attribute? :branches_to_be_notified, T::String.optional
    attribute? :disable_diffs, T::Bool.optional
    attribute? :push_events, T::Bool.optional
    attribute? :send_from_committer_email, T::Bool.optional
    attribute? :tag_push_events, T::Bool.optional
  end
end
