# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_branch/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabBranch
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_branch,
      attributes_class: Gitlab::Types::BranchAttributes,
      outputs: { id: :id },
      map: [:name, :project, :ref],
      map_bool: [:keep_on_destroy]
  end
  module Gitlab
    include GitlabBranch
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
