# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class BranchAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :name, T::String
    attribute :project, T::String
    attribute :ref, T::String
    attribute? :keep_on_destroy, T::Bool.optional
  end
end
