# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class GroupServiceAccountAccessTokenAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :group, T::String
    attribute :name, T::String
    attribute :scopes, T::Array.of(T::String)
    attribute :user_id, T::Float
    attribute? :rotation_configuration, T::Hash.optional
  end
end
