# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_user_identity/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabUserIdentity
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_user_identity,
      attributes_class: Gitlab::Types::UserIdentityAttributes,
      outputs: { id: :id },
      map: [:external_provider, :external_uid, :user_id]
  end
  module Gitlab
    include GitlabUserIdentity
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
