# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_service_github/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabServiceGithub
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_service_github,
      attributes_class: Gitlab::Types::ServiceGithubAttributes,
      outputs: { id: :id },
      map: [:project, :repository_url, :token],
      map_bool: [:static_context]
  end
  module Gitlab
    include GitlabServiceGithub
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
