# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_pages_domain/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabPagesDomain
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_pages_domain,
      attributes_class: Gitlab::Types::PagesDomainAttributes,
      outputs: { id: :id },
      map: [:domain, :project],
      map_present: [:key]
  end
  module Gitlab
    include GitlabPagesDomain
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
