# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class PagesDomainAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :domain, T::String
    attribute :project, T::String
    attribute? :key, T::String.optional
  end
end
