# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_project_access_token/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabProjectAccessToken
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_project_access_token,
      attributes_class: Gitlab::Types::ProjectAccessTokenAttributes,
      outputs: { id: :id },
      map: [:name, :project, :scopes],
      map_present: [:rotation_configuration]
  end
  module Gitlab
    include GitlabProjectAccessToken
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
