# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_deploy_key_enable/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabDeployKeyEnable
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_deploy_key_enable,
      attributes_class: Gitlab::Types::DeployKeyEnableAttributes,
      outputs: { id: :id },
      map: [:key_id, :project],
      map_bool: [:can_push]
  end
  module Gitlab
    include GitlabDeployKeyEnable
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
