# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class GroupAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :name, T::String
    attribute :path, T::String
    attribute? :avatar, T::String.optional
    attribute? :default_branch, T::String.optional
    attribute? :default_branch_protection_defaults, T::Array.of(T::Hash).optional
    attribute? :description, T::String.optional
    attribute? :ip_restriction_ranges, T::Array.of(T::String).optional
    attribute? :permanently_remove_on_delete, T::Bool.optional
    attribute? :push_rules, T::Array.of(T::Hash).optional
  end
end
