# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class RepositoryFileAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :branch, T::String
    attribute :content, T::String
    attribute :file_path, T::String
    attribute :project, T::String
    attribute? :author_email, T::String.optional
    attribute? :author_name, T::String.optional
    attribute? :commit_message, T::String.optional
    attribute? :create_commit_message, T::String.optional
    attribute? :delete_commit_message, T::String.optional
    attribute? :encoding, T::String.optional
    attribute? :execute_filemode, T::Bool.optional
    attribute? :overwrite_on_create, T::Bool.optional
    attribute? :start_branch, T::String.optional
    attribute? :update_commit_message, T::String.optional
  end
end
