# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class ValueStreamAnalyticsAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :name, T::String
    attribute :stages, T::Array.of(T::Hash)
    attribute? :group_full_path, T::String.optional
    attribute? :project_full_path, T::String.optional
  end
end
