# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_pipeline_schedule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabPipelineSchedule
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_pipeline_schedule,
      attributes_class: Gitlab::Types::PipelineScheduleAttributes,
      outputs: { id: :id },
      map: [:cron, :description, :project, :ref]
  end
  module Gitlab
    include GitlabPipelineSchedule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
