# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_project_target_branch_rule/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabProjectTargetBranchRule
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_project_target_branch_rule,
      attributes_class: Gitlab::Types::ProjectTargetBranchRuleAttributes,
      outputs: { id: :id },
      map: [:project, :source_branch_pattern, :target_branch_name]
  end
  module Gitlab
    include GitlabProjectTargetBranchRule
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
