# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_group_service_account/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabGroupServiceAccount
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_group_service_account,
      attributes_class: Gitlab::Types::GroupServiceAccountAttributes,
      outputs: { id: :id },
      map: [:group],
      map_present: [:name, :username]
  end
  module Gitlab
    include GitlabGroupServiceAccount
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
