# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class GroupServiceAccountAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :group, T::String
    attribute? :name, T::String.optional
    attribute? :username, T::String.optional
  end
end
