# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_project_custom_attribute/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabProjectCustomAttribute
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_project_custom_attribute,
      attributes_class: Gitlab::Types::ProjectCustomAttributeAttributes,
      outputs: { id: :id },
      map: [:key, :project, :value]
  end
  module Gitlab
    include GitlabProjectCustomAttribute
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
