# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class TagProtectionAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :project, T::String
    attribute :tag, T::String
    attribute? :allowed_to_create, T::Array.of(T::Hash).optional
  end
end
