# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_integration_custom_issue_tracker/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabIntegrationCustomIssueTracker
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_integration_custom_issue_tracker,
      attributes_class: Gitlab::Types::IntegrationCustomIssueTrackerAttributes,
      outputs: { id: :id },
      map: [:issues_url, :project, :project_url]
  end
  module Gitlab
    include GitlabIntegrationCustomIssueTracker
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
