# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_release/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabRelease
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_release,
      attributes_class: Gitlab::Types::ReleaseAttributes,
      outputs: { id: :id },
      map: [:project, :tag_name],
      map_present: [:milestones, :tag_message]
  end
  module Gitlab
    include GitlabRelease
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
