# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class ReleaseAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :project, T::String
    attribute :tag_name, T::String
    attribute? :milestones, T::Array.of(T::String).optional
    attribute? :tag_message, T::String.optional
  end
end
