# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_group_saml_link/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabGroupSamlLink
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_group_saml_link,
      attributes_class: Gitlab::Types::GroupSamlLinkAttributes,
      outputs: { id: :id },
      map: [:access_level, :group, :saml_group_name],
      map_present: [:member_role_id]
  end
  module Gitlab
    include GitlabGroupSamlLink
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
