# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class GroupSamlLinkAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :access_level, T::String
    attribute :group, T::String
    attribute :saml_group_name, T::String
    attribute? :member_role_id, T::Float.optional
  end
end
