# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'dry-struct'

module Pangea::Resources::Gitlab::Types
  include Dry.Types()

  class GroupLdapLinkAttributes < Dry::Struct
    transform_keys(&:to_sym)
    T = Pangea::Resources::Gitlab::Types

    attribute :group, T::String
    attribute :ldap_provider, T::String
    attribute? :access_level, T::String.optional
    attribute? :force, T::Bool.optional
    attribute? :group_access, T::String.optional
  end
end
