# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_project_compliance_framework/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabProjectComplianceFramework
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_project_compliance_framework,
      attributes_class: Gitlab::Types::ProjectComplianceFrameworkAttributes,
      outputs: { id: :id },
      map: [:compliance_framework_id, :project]
  end
  module Gitlab
    include GitlabProjectComplianceFramework
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
