# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_project_issue/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabProjectIssue
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_project_issue,
      attributes_class: Gitlab::Types::ProjectIssueAttributes,
      outputs: { id: :id },
      map: [:project, :title],
      map_present: [:assignee_ids, :description, :discussion_to_resolve, :due_date, :issue_type, :labels, :merge_request_to_resolve_discussions_of, :milestone_id, :state],
      map_bool: [:confidential, :delete_on_destroy, :discussion_locked]
  end
  module Gitlab
    include GitlabProjectIssue
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
