# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_deploy_key resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabDeployKey do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { key: 'test-value', project: 'test-value', title: 'test-value' } }

  describe ':gitlab_deploy_key' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_deploy_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_deploy_key', 'test')
        validate_required_attributes(config, [:key, :project, :title])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_deploy_key('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_deploy_key)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_deploy_key('test', required_attrs)

        expect(ref.id).to eq("${gitlab_deploy_key.test.id}")
        expect(ref.deploy_key_id).to eq("${gitlab_deploy_key.test.deploy_key_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_deploy_key('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_deploy_key', 'test')
        expect(config).not_to have_key('deploy_key_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ can_push: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_deploy_key('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_deploy_key', 'full')
        expect(config).to have_key('can_push')
      end
    end

    context 'optional attributes' do
      it 'includes can_push when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_deploy_key('opt', required_attrs.merge(can_push: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_deploy_key', 'opt')
        expect(config).to have_key('can_push')
      end

      it 'omits can_push when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_deploy_key('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_deploy_key', 'minimal')
        expect(config).not_to have_key('can_push')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts can_push=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(can_push: val)
          synth.gitlab_deploy_key("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_deploy_key', "bool_#{val}")
          expect(config['can_push']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_deploy_key('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_deploy_key', 'typed')
        expect(config['key']).to be_a(String)
        expect(config['project']).to be_a(String)
        expect(config['title']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_deploy_key('first', required_attrs)
        synth.gitlab_deploy_key('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_deploy_key')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_deploy_key,
    method: :gitlab_deploy_key,
    required_attrs: { key: 'test-value', project: 'test-value', title: 'test-value' },
    expected_outputs: [:id, :deploy_key_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:can_push]
end
