# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_group_membership resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabGroupMembership do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { access_level: 'test-value', group_id: 3.14, user_id: 3.14 } }

  describe ':gitlab_group_membership' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_membership('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_group_membership', 'test')
        validate_required_attributes(config, [:access_level, :group_id, :user_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_group_membership('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_group_membership)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_group_membership('test', required_attrs)

        expect(ref.id).to eq("${gitlab_group_membership.test.id}")
        expect(ref.expires_at).to eq("${gitlab_group_membership.test.expires_at}")
        expect(ref.member_role_id).to eq("${gitlab_group_membership.test.member_role_id}")
        expect(ref.skip_subresources_on_destroy).to eq("${gitlab_group_membership.test.skip_subresources_on_destroy}")
        expect(ref.unassign_issuables_on_destroy).to eq("${gitlab_group_membership.test.unassign_issuables_on_destroy}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_membership('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_group_membership', 'test')
        expect(config).not_to have_key('expires_at')
        expect(config).not_to have_key('member_role_id')
        expect(config).not_to have_key('skip_subresources_on_destroy')
        expect(config).not_to have_key('unassign_issuables_on_destroy')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_membership('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_group_membership', 'typed')
        expect(config['access_level']).to be_a(String)
        expect(config['group_id']).to be_a(Float)
        expect(config['user_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_membership('first', required_attrs)
        synth.gitlab_group_membership('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_group_membership')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_group_membership,
    method: :gitlab_group_membership,
    required_attrs: { access_level: 'test-value', group_id: 3.14, user_id: 3.14 },
    expected_outputs: [:id, :expires_at, :member_role_id, :skip_subresources_on_destroy, :unassign_issuables_on_destroy],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
