# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_pipeline_trigger resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabPipelineTrigger do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { description: 'test-value', project: 'test-value' } }

  describe ':gitlab_pipeline_trigger' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_pipeline_trigger('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_pipeline_trigger', 'test')
        validate_required_attributes(config, [:description, :project])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_pipeline_trigger('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_pipeline_trigger)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_pipeline_trigger('test', required_attrs)

        expect(ref.id).to eq("${gitlab_pipeline_trigger.test.id}")
        expect(ref.pipeline_trigger_id).to eq("${gitlab_pipeline_trigger.test.pipeline_trigger_id}")
        expect(ref.token).to eq("${gitlab_pipeline_trigger.test.token}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_pipeline_trigger('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_pipeline_trigger', 'test')
        expect(config).not_to have_key('pipeline_trigger_id')
        expect(config).not_to have_key('token')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:token]
        expect(sensitive_fields).to include(:token)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_pipeline_trigger('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_pipeline_trigger', 'typed')
        expect(config['description']).to be_a(String)
        expect(config['project']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_pipeline_trigger('first', required_attrs)
        synth.gitlab_pipeline_trigger('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_pipeline_trigger')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_pipeline_trigger,
    method: :gitlab_pipeline_trigger,
    required_attrs: { description: 'test-value', project: 'test-value' },
    expected_outputs: [:id, :pipeline_trigger_id, :token],
    sensitive_fields: [:token],
    immutable_fields: [],
    boolean_fields: []
end
