# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_pipeline_schedule_variable resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabPipelineScheduleVariable do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { key: 'test-value', pipeline_schedule_id: 3.14, project: 'test-value', value: 'test-value' } }

  describe ':gitlab_pipeline_schedule_variable' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_pipeline_schedule_variable('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_pipeline_schedule_variable', 'test')
        validate_required_attributes(config, [:key, :pipeline_schedule_id, :project, :value])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_pipeline_schedule_variable('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_pipeline_schedule_variable)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_pipeline_schedule_variable('test', required_attrs)

        expect(ref.id).to eq("${gitlab_pipeline_schedule_variable.test.id}")
        expect(ref.variable_type).to eq("${gitlab_pipeline_schedule_variable.test.variable_type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_pipeline_schedule_variable('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_pipeline_schedule_variable', 'test')
        expect(config).not_to have_key('variable_type')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_pipeline_schedule_variable('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_pipeline_schedule_variable', 'typed')
        expect(config['key']).to be_a(String)
        expect(config['pipeline_schedule_id']).to be_a(Float)
        expect(config['project']).to be_a(String)
        expect(config['value']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_pipeline_schedule_variable('first', required_attrs)
        synth.gitlab_pipeline_schedule_variable('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_pipeline_schedule_variable')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_pipeline_schedule_variable,
    method: :gitlab_pipeline_schedule_variable,
    required_attrs: { key: 'test-value', pipeline_schedule_id: 3.14, project: 'test-value', value: 'test-value' },
    expected_outputs: [:id, :variable_type],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
