# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_project_push_rules resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabProjectPushRules do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project: 'test-value' } }

  describe ':gitlab_project_push_rules' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_push_rules('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_project_push_rules', 'test')
        validate_required_attributes(config, [:project])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_push_rules('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_project_push_rules)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_push_rules('test', required_attrs)

        expect(ref.id).to eq("${gitlab_project_push_rules.test.id}")
        expect(ref.author_email_regex).to eq("${gitlab_project_push_rules.test.author_email_regex}")
        expect(ref.branch_name_regex).to eq("${gitlab_project_push_rules.test.branch_name_regex}")
        expect(ref.commit_committer_check).to eq("${gitlab_project_push_rules.test.commit_committer_check}")
        expect(ref.commit_committer_name_check).to eq("${gitlab_project_push_rules.test.commit_committer_name_check}")
        expect(ref.commit_message_negative_regex).to eq("${gitlab_project_push_rules.test.commit_message_negative_regex}")
        expect(ref.commit_message_regex).to eq("${gitlab_project_push_rules.test.commit_message_regex}")
        expect(ref.deny_delete_tag).to eq("${gitlab_project_push_rules.test.deny_delete_tag}")
        expect(ref.file_name_regex).to eq("${gitlab_project_push_rules.test.file_name_regex}")
        expect(ref.max_file_size).to eq("${gitlab_project_push_rules.test.max_file_size}")
        expect(ref.member_check).to eq("${gitlab_project_push_rules.test.member_check}")
        expect(ref.prevent_secrets).to eq("${gitlab_project_push_rules.test.prevent_secrets}")
        expect(ref.reject_non_dco_commits).to eq("${gitlab_project_push_rules.test.reject_non_dco_commits}")
        expect(ref.reject_unsigned_commits).to eq("${gitlab_project_push_rules.test.reject_unsigned_commits}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_push_rules('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_push_rules', 'test')
        expect(config).not_to have_key('author_email_regex')
        expect(config).not_to have_key('branch_name_regex')
        expect(config).not_to have_key('commit_committer_check')
        expect(config).not_to have_key('commit_committer_name_check')
        expect(config).not_to have_key('commit_message_negative_regex')
        expect(config).not_to have_key('commit_message_regex')
        expect(config).not_to have_key('deny_delete_tag')
        expect(config).not_to have_key('file_name_regex')
        expect(config).not_to have_key('max_file_size')
        expect(config).not_to have_key('member_check')
        expect(config).not_to have_key('prevent_secrets')
        expect(config).not_to have_key('reject_non_dco_commits')
        expect(config).not_to have_key('reject_unsigned_commits')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_push_rules('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_push_rules', 'typed')
        expect(config['project']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_push_rules('first', required_attrs)
        synth.gitlab_project_push_rules('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_project_push_rules')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_project_push_rules,
    method: :gitlab_project_push_rules,
    required_attrs: { project: 'test-value' },
    expected_outputs: [:id, :author_email_regex, :branch_name_regex, :commit_committer_check, :commit_committer_name_check, :commit_message_negative_regex, :commit_message_regex, :deny_delete_tag, :file_name_regex, :max_file_size, :member_check, :prevent_secrets, :reject_non_dco_commits, :reject_unsigned_commits],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
