# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_deploy_token resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabDeployToken do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', scopes: ['test-value'] } }

  describe ':gitlab_deploy_token' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_deploy_token('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_deploy_token', 'test')
        validate_required_attributes(config, [:name, :scopes])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_deploy_token('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_deploy_token)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_deploy_token('test', required_attrs)

        expect(ref.id).to eq("${gitlab_deploy_token.test.id}")
        expect(ref.deploy_token_id).to eq("${gitlab_deploy_token.test.deploy_token_id}")
        expect(ref.token).to eq("${gitlab_deploy_token.test.token}")
        expect(ref.username).to eq("${gitlab_deploy_token.test.username}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_deploy_token('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_deploy_token', 'test')
        expect(config).not_to have_key('deploy_token_id')
        expect(config).not_to have_key('token')
        expect(config).not_to have_key('username')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ expires_at: 'test-value', group: 'test-value', project: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_deploy_token('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_deploy_token', 'full')
        expect(config).to have_key('expires_at')
        expect(config).to have_key('group')
        expect(config).to have_key('project')
      end
    end

    context 'optional attributes' do
      it 'includes expires_at when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_deploy_token('opt', required_attrs.merge(expires_at: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_deploy_token', 'opt')
        expect(config).to have_key('expires_at')
      end

      it 'omits expires_at when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_deploy_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_deploy_token', 'minimal')
        expect(config).not_to have_key('expires_at')
      end
      it 'includes group when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_deploy_token('opt', required_attrs.merge(group: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_deploy_token', 'opt')
        expect(config).to have_key('group')
      end

      it 'omits group when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_deploy_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_deploy_token', 'minimal')
        expect(config).not_to have_key('group')
      end
      it 'includes project when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_deploy_token('opt', required_attrs.merge(project: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_deploy_token', 'opt')
        expect(config).to have_key('project')
      end

      it 'omits project when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_deploy_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_deploy_token', 'minimal')
        expect(config).not_to have_key('project')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:token]
        expect(sensitive_fields).to include(:token)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_deploy_token('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_deploy_token', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['scopes']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_deploy_token('first', required_attrs)
        synth.gitlab_deploy_token('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_deploy_token')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_deploy_token,
    method: :gitlab_deploy_token,
    required_attrs: { name: 'test-value', scopes: ['test-value'] },
    expected_outputs: [:id, :deploy_token_id, :token, :username],
    sensitive_fields: [:token],
    immutable_fields: [],
    boolean_fields: []
end
