# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_group_project_file_template resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabGroupProjectFileTemplate do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { file_template_project_id: 3.14, group_id: 3.14 } }

  describe ':gitlab_group_project_file_template' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_project_file_template('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_group_project_file_template', 'test')
        validate_required_attributes(config, [:file_template_project_id, :group_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_group_project_file_template('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_group_project_file_template)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_group_project_file_template('test', required_attrs)

        expect(ref.id).to eq("${gitlab_group_project_file_template.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_project_file_template('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_group_project_file_template', 'typed')
        expect(config['file_template_project_id']).to be_a(Float)
        expect(config['group_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_project_file_template('first', required_attrs)
        synth.gitlab_group_project_file_template('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_group_project_file_template')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_group_project_file_template,
    method: :gitlab_group_project_file_template,
    required_attrs: { file_template_project_id: 3.14, group_id: 3.14 },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
