# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_group_share_group resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabGroupShareGroup do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { group_access: 'test-value', group_id: 'test-value', share_group_id: 3.14 } }

  describe ':gitlab_group_share_group' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_share_group('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_group_share_group', 'test')
        validate_required_attributes(config, [:group_access, :group_id, :share_group_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_group_share_group('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_group_share_group)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_group_share_group('test', required_attrs)

        expect(ref.id).to eq("${gitlab_group_share_group.test.id}")
        expect(ref.member_role_id).to eq("${gitlab_group_share_group.test.member_role_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_share_group('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_group_share_group', 'test')
        expect(config).not_to have_key('member_role_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ expires_at: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_share_group('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_group_share_group', 'full')
        expect(config).to have_key('expires_at')
      end
    end

    context 'optional attributes' do
      it 'includes expires_at when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_share_group('opt', required_attrs.merge(expires_at: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group_share_group', 'opt')
        expect(config).to have_key('expires_at')
      end

      it 'omits expires_at when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_share_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group_share_group', 'minimal')
        expect(config).not_to have_key('expires_at')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_share_group('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_group_share_group', 'typed')
        expect(config['group_access']).to be_a(String)
        expect(config['group_id']).to be_a(String)
        expect(config['share_group_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_share_group('first', required_attrs)
        synth.gitlab_group_share_group('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_group_share_group')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_group_share_group,
    method: :gitlab_group_share_group,
    required_attrs: { group_access: 'test-value', group_id: 'test-value', share_group_id: 3.14 },
    expected_outputs: [:id, :member_role_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
