# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_system_hook resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabSystemHook do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { url: 'test-value' } }

  describe ':gitlab_system_hook' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_system_hook('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_system_hook', 'test')
        validate_required_attributes(config, [:url])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_system_hook('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_system_hook)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_system_hook('test', required_attrs)

        expect(ref.id).to eq("${gitlab_system_hook.test.id}")
        expect(ref.created_at).to eq("${gitlab_system_hook.test.created_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_system_hook('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_system_hook', 'test')
        expect(config).not_to have_key('created_at')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ enable_ssl_verification: true, merge_requests_events: true, push_events: true, repository_update_events: true, tag_push_events: true, token: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_system_hook('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_system_hook', 'full')
        expect(config).to have_key('enable_ssl_verification')
        expect(config).to have_key('merge_requests_events')
        expect(config).to have_key('push_events')
        expect(config).to have_key('repository_update_events')
        expect(config).to have_key('tag_push_events')
        expect(config).to have_key('token')
      end
    end

    context 'optional attributes' do
      it 'includes enable_ssl_verification when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_system_hook('opt', required_attrs.merge(enable_ssl_verification: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_system_hook', 'opt')
        expect(config).to have_key('enable_ssl_verification')
      end

      it 'omits enable_ssl_verification when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_system_hook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_system_hook', 'minimal')
        expect(config).not_to have_key('enable_ssl_verification')
      end
      it 'includes merge_requests_events when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_system_hook('opt', required_attrs.merge(merge_requests_events: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_system_hook', 'opt')
        expect(config).to have_key('merge_requests_events')
      end

      it 'omits merge_requests_events when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_system_hook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_system_hook', 'minimal')
        expect(config).not_to have_key('merge_requests_events')
      end
      it 'includes push_events when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_system_hook('opt', required_attrs.merge(push_events: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_system_hook', 'opt')
        expect(config).to have_key('push_events')
      end

      it 'omits push_events when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_system_hook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_system_hook', 'minimal')
        expect(config).not_to have_key('push_events')
      end
      it 'includes repository_update_events when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_system_hook('opt', required_attrs.merge(repository_update_events: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_system_hook', 'opt')
        expect(config).to have_key('repository_update_events')
      end

      it 'omits repository_update_events when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_system_hook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_system_hook', 'minimal')
        expect(config).not_to have_key('repository_update_events')
      end
      it 'includes tag_push_events when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_system_hook('opt', required_attrs.merge(tag_push_events: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_system_hook', 'opt')
        expect(config).to have_key('tag_push_events')
      end

      it 'omits tag_push_events when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_system_hook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_system_hook', 'minimal')
        expect(config).not_to have_key('tag_push_events')
      end
      it 'includes token when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_system_hook('opt', required_attrs.merge(token: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_system_hook', 'opt')
        expect(config).to have_key('token')
      end

      it 'omits token when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_system_hook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_system_hook', 'minimal')
        expect(config).not_to have_key('token')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:token]
        expect(sensitive_fields).to include(:token)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enable_ssl_verification=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enable_ssl_verification: val)
          synth.gitlab_system_hook("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_system_hook', "bool_#{val}")
          expect(config['enable_ssl_verification']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts merge_requests_events=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(merge_requests_events: val)
          synth.gitlab_system_hook("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_system_hook', "bool_#{val}")
          expect(config['merge_requests_events']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts push_events=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(push_events: val)
          synth.gitlab_system_hook("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_system_hook', "bool_#{val}")
          expect(config['push_events']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts repository_update_events=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(repository_update_events: val)
          synth.gitlab_system_hook("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_system_hook', "bool_#{val}")
          expect(config['repository_update_events']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts tag_push_events=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(tag_push_events: val)
          synth.gitlab_system_hook("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_system_hook', "bool_#{val}")
          expect(config['tag_push_events']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_system_hook('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_system_hook', 'typed')
        expect(config['url']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_system_hook('first', required_attrs)
        synth.gitlab_system_hook('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_system_hook')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_system_hook,
    method: :gitlab_system_hook,
    required_attrs: { url: 'test-value' },
    expected_outputs: [:id, :created_at],
    sensitive_fields: [:token],
    immutable_fields: [],
    boolean_fields: [:enable_ssl_verification, :merge_requests_events, :push_events, :repository_update_events, :tag_push_events]
end
