# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_instance_variable resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabInstanceVariable do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { key: 'test-value', value: 'test-value' } }

  describe ':gitlab_instance_variable' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_instance_variable('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_instance_variable', 'test')
        validate_required_attributes(config, [:key, :value])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_instance_variable('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_instance_variable)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_instance_variable('test', required_attrs)

        expect(ref.id).to eq("${gitlab_instance_variable.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', masked: true, protected: true, raw: true, variable_type: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_instance_variable('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_instance_variable', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('masked')
        expect(config).to have_key('protected')
        expect(config).to have_key('raw')
        expect(config).to have_key('variable_type')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_instance_variable('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_instance_variable', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_instance_variable('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_instance_variable', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes masked when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_instance_variable('opt', required_attrs.merge(masked: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_instance_variable', 'opt')
        expect(config).to have_key('masked')
      end

      it 'omits masked when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_instance_variable('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_instance_variable', 'minimal')
        expect(config).not_to have_key('masked')
      end
      it 'includes protected when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_instance_variable('opt', required_attrs.merge(protected: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_instance_variable', 'opt')
        expect(config).to have_key('protected')
      end

      it 'omits protected when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_instance_variable('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_instance_variable', 'minimal')
        expect(config).not_to have_key('protected')
      end
      it 'includes raw when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_instance_variable('opt', required_attrs.merge(raw: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_instance_variable', 'opt')
        expect(config).to have_key('raw')
      end

      it 'omits raw when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_instance_variable('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_instance_variable', 'minimal')
        expect(config).not_to have_key('raw')
      end
      it 'includes variable_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_instance_variable('opt', required_attrs.merge(variable_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_instance_variable', 'opt')
        expect(config).to have_key('variable_type')
      end

      it 'omits variable_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_instance_variable('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_instance_variable', 'minimal')
        expect(config).not_to have_key('variable_type')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts masked=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(masked: val)
          synth.gitlab_instance_variable("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_instance_variable', "bool_#{val}")
          expect(config['masked']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts protected=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(protected: val)
          synth.gitlab_instance_variable("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_instance_variable', "bool_#{val}")
          expect(config['protected']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts raw=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(raw: val)
          synth.gitlab_instance_variable("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_instance_variable', "bool_#{val}")
          expect(config['raw']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_instance_variable('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_instance_variable', 'typed')
        expect(config['key']).to be_a(String)
        expect(config['value']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_instance_variable('first', required_attrs)
        synth.gitlab_instance_variable('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_instance_variable')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_instance_variable,
    method: :gitlab_instance_variable,
    required_attrs: { key: 'test-value', value: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:masked, :protected, :raw]
end
