# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_project_approval_rule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabProjectApprovalRule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { approvals_required: 3.14, name: 'test-value', project: 'test-value' } }

  describe ':gitlab_project_approval_rule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_approval_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_project_approval_rule', 'test')
        validate_required_attributes(config, [:approvals_required, :name, :project])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_approval_rule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_project_approval_rule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_approval_rule('test', required_attrs)

        expect(ref.id).to eq("${gitlab_project_approval_rule.test.id}")
        expect(ref.report_type).to eq("${gitlab_project_approval_rule.test.report_type}")
        expect(ref.rule_type).to eq("${gitlab_project_approval_rule.test.rule_type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_approval_rule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_approval_rule', 'test')
        expect(config).not_to have_key('report_type')
        expect(config).not_to have_key('rule_type')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ applies_to_all_protected_branches: true, disable_importing_default_any_approver_rule_on_create: true, group_ids: [3.14], protected_branch_ids: [3.14], user_ids: [3.14] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_approval_rule('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_approval_rule', 'full')
        expect(config).to have_key('applies_to_all_protected_branches')
        expect(config).to have_key('disable_importing_default_any_approver_rule_on_create')
        expect(config).to have_key('group_ids')
        expect(config).to have_key('protected_branch_ids')
        expect(config).to have_key('user_ids')
      end
    end

    context 'optional attributes' do
      it 'includes applies_to_all_protected_branches when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_approval_rule('opt', required_attrs.merge(applies_to_all_protected_branches: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_approval_rule', 'opt')
        expect(config).to have_key('applies_to_all_protected_branches')
      end

      it 'omits applies_to_all_protected_branches when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_approval_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_approval_rule', 'minimal')
        expect(config).not_to have_key('applies_to_all_protected_branches')
      end
      it 'includes disable_importing_default_any_approver_rule_on_create when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_approval_rule('opt', required_attrs.merge(disable_importing_default_any_approver_rule_on_create: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_approval_rule', 'opt')
        expect(config).to have_key('disable_importing_default_any_approver_rule_on_create')
      end

      it 'omits disable_importing_default_any_approver_rule_on_create when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_approval_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_approval_rule', 'minimal')
        expect(config).not_to have_key('disable_importing_default_any_approver_rule_on_create')
      end
      it 'includes group_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_approval_rule('opt', required_attrs.merge(group_ids: [3.14]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_approval_rule', 'opt')
        expect(config).to have_key('group_ids')
      end

      it 'omits group_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_approval_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_approval_rule', 'minimal')
        expect(config).not_to have_key('group_ids')
      end
      it 'includes protected_branch_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_approval_rule('opt', required_attrs.merge(protected_branch_ids: [3.14]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_approval_rule', 'opt')
        expect(config).to have_key('protected_branch_ids')
      end

      it 'omits protected_branch_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_approval_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_approval_rule', 'minimal')
        expect(config).not_to have_key('protected_branch_ids')
      end
      it 'includes user_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_approval_rule('opt', required_attrs.merge(user_ids: [3.14]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_approval_rule', 'opt')
        expect(config).to have_key('user_ids')
      end

      it 'omits user_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_approval_rule('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_approval_rule', 'minimal')
        expect(config).not_to have_key('user_ids')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts applies_to_all_protected_branches=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(applies_to_all_protected_branches: val)
          synth.gitlab_project_approval_rule("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_project_approval_rule', "bool_#{val}")
          expect(config['applies_to_all_protected_branches']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts disable_importing_default_any_approver_rule_on_create=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(disable_importing_default_any_approver_rule_on_create: val)
          synth.gitlab_project_approval_rule("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_project_approval_rule', "bool_#{val}")
          expect(config['disable_importing_default_any_approver_rule_on_create']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_approval_rule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_approval_rule', 'typed')
        expect(config['approvals_required']).to be_a(Float)
        expect(config['name']).to be_a(String)
        expect(config['project']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_approval_rule('first', required_attrs)
        synth.gitlab_project_approval_rule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_project_approval_rule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_project_approval_rule,
    method: :gitlab_project_approval_rule,
    required_attrs: { approvals_required: 3.14, name: 'test-value', project: 'test-value' },
    expected_outputs: [:id, :report_type, :rule_type],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:applies_to_all_protected_branches, :disable_importing_default_any_approver_rule_on_create]
end
