# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_group_variable resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabGroupVariable do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { group: 'test-value', key: 'test-value', value: 'test-value' } }

  describe ':gitlab_group_variable' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_variable('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_group_variable', 'test')
        validate_required_attributes(config, [:group, :key, :value])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_group_variable('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_group_variable)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_group_variable('test', required_attrs)

        expect(ref.id).to eq("${gitlab_group_variable.test.id}")
        expect(ref.description).to eq("${gitlab_group_variable.test.description}")
        expect(ref.environment_scope).to eq("${gitlab_group_variable.test.environment_scope}")
        expect(ref.hidden).to eq("${gitlab_group_variable.test.hidden}")
        expect(ref.masked).to eq("${gitlab_group_variable.test.masked}")
        expect(ref.protected).to eq("${gitlab_group_variable.test.protected}")
        expect(ref.raw).to eq("${gitlab_group_variable.test.raw}")
        expect(ref.variable_type).to eq("${gitlab_group_variable.test.variable_type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_variable('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_group_variable', 'test')
        expect(config).not_to have_key('description')
        expect(config).not_to have_key('environment_scope')
        expect(config).not_to have_key('hidden')
        expect(config).not_to have_key('masked')
        expect(config).not_to have_key('protected')
        expect(config).not_to have_key('raw')
        expect(config).not_to have_key('variable_type')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_variable('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_group_variable', 'typed')
        expect(config['group']).to be_a(String)
        expect(config['key']).to be_a(String)
        expect(config['value']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_variable('first', required_attrs)
        synth.gitlab_group_variable('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_group_variable')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_group_variable,
    method: :gitlab_group_variable,
    required_attrs: { group: 'test-value', key: 'test-value', value: 'test-value' },
    expected_outputs: [:id, :description, :environment_scope, :hidden, :masked, :protected, :raw, :variable_type],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
