# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_project_hook resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabProjectHook do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project: 'test-value', url: 'test-value' } }

  describe ':gitlab_project_hook' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_hook('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_project_hook', 'test')
        validate_required_attributes(config, [:project, :url])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_hook('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_project_hook)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_hook('test', required_attrs)

        expect(ref.id).to eq("${gitlab_project_hook.test.id}")
        expect(ref.confidential_issues_events).to eq("${gitlab_project_hook.test.confidential_issues_events}")
        expect(ref.confidential_note_events).to eq("${gitlab_project_hook.test.confidential_note_events}")
        expect(ref.custom_webhook_template).to eq("${gitlab_project_hook.test.custom_webhook_template}")
        expect(ref.deployment_events).to eq("${gitlab_project_hook.test.deployment_events}")
        expect(ref.description).to eq("${gitlab_project_hook.test.description}")
        expect(ref.enable_ssl_verification).to eq("${gitlab_project_hook.test.enable_ssl_verification}")
        expect(ref.hook_id).to eq("${gitlab_project_hook.test.hook_id}")
        expect(ref.issues_events).to eq("${gitlab_project_hook.test.issues_events}")
        expect(ref.job_events).to eq("${gitlab_project_hook.test.job_events}")
        expect(ref.merge_requests_events).to eq("${gitlab_project_hook.test.merge_requests_events}")
        expect(ref.name).to eq("${gitlab_project_hook.test.name}")
        expect(ref.note_events).to eq("${gitlab_project_hook.test.note_events}")
        expect(ref.pipeline_events).to eq("${gitlab_project_hook.test.pipeline_events}")
        expect(ref.project_id).to eq("${gitlab_project_hook.test.project_id}")
        expect(ref.push_events).to eq("${gitlab_project_hook.test.push_events}")
        expect(ref.push_events_branch_filter).to eq("${gitlab_project_hook.test.push_events_branch_filter}")
        expect(ref.releases_events).to eq("${gitlab_project_hook.test.releases_events}")
        expect(ref.resource_access_token_events).to eq("${gitlab_project_hook.test.resource_access_token_events}")
        expect(ref.tag_push_events).to eq("${gitlab_project_hook.test.tag_push_events}")
        expect(ref.token).to eq("${gitlab_project_hook.test.token}")
        expect(ref.wiki_page_events).to eq("${gitlab_project_hook.test.wiki_page_events}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_hook('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_hook', 'test')
        expect(config).not_to have_key('confidential_issues_events')
        expect(config).not_to have_key('confidential_note_events')
        expect(config).not_to have_key('custom_webhook_template')
        expect(config).not_to have_key('deployment_events')
        expect(config).not_to have_key('description')
        expect(config).not_to have_key('enable_ssl_verification')
        expect(config).not_to have_key('hook_id')
        expect(config).not_to have_key('issues_events')
        expect(config).not_to have_key('job_events')
        expect(config).not_to have_key('merge_requests_events')
        expect(config).not_to have_key('name')
        expect(config).not_to have_key('note_events')
        expect(config).not_to have_key('pipeline_events')
        expect(config).not_to have_key('project_id')
        expect(config).not_to have_key('push_events')
        expect(config).not_to have_key('push_events_branch_filter')
        expect(config).not_to have_key('releases_events')
        expect(config).not_to have_key('resource_access_token_events')
        expect(config).not_to have_key('tag_push_events')
        expect(config).not_to have_key('token')
        expect(config).not_to have_key('wiki_page_events')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ custom_headers: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_hook('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_hook', 'full')
        expect(config).to have_key('custom_headers')
      end
    end

    context 'optional attributes' do
      it 'includes custom_headers when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_hook('opt', required_attrs.merge(custom_headers: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_hook', 'opt')
        expect(config).to have_key('custom_headers')
      end

      it 'omits custom_headers when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_hook('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_hook', 'minimal')
        expect(config).not_to have_key('custom_headers')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:token]
        expect(sensitive_fields).to include(:token)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_hook('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_hook', 'typed')
        expect(config['project']).to be_a(String)
        expect(config['url']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_hook('first', required_attrs)
        synth.gitlab_project_hook('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_project_hook')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_project_hook,
    method: :gitlab_project_hook,
    required_attrs: { project: 'test-value', url: 'test-value' },
    expected_outputs: [:id, :confidential_issues_events, :confidential_note_events, :custom_webhook_template, :deployment_events, :description, :enable_ssl_verification, :hook_id, :issues_events, :job_events, :merge_requests_events, :name, :note_events, :pipeline_events, :project_id, :push_events, :push_events_branch_filter, :releases_events, :resource_access_token_events, :tag_push_events, :token, :wiki_page_events],
    sensitive_fields: [:token],
    immutable_fields: [],
    boolean_fields: []
end
