# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_integration_microsoft_teams resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabIntegrationMicrosoftTeams do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project: 'test-value', webhook: 'test-value' } }

  describe ':gitlab_integration_microsoft_teams' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'test')
        validate_required_attributes(config, [:project, :webhook])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_integration_microsoft_teams('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_integration_microsoft_teams)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_integration_microsoft_teams('test', required_attrs)

        expect(ref.id).to eq("${gitlab_integration_microsoft_teams.test.id}")
        expect(ref.active).to eq("${gitlab_integration_microsoft_teams.test.active}")
        expect(ref.created_at).to eq("${gitlab_integration_microsoft_teams.test.created_at}")
        expect(ref.updated_at).to eq("${gitlab_integration_microsoft_teams.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'test')
        expect(config).not_to have_key('active')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ branches_to_be_notified: 'test-value', confidential_issues_events: true, confidential_note_events: true, issues_events: true, merge_requests_events: true, note_events: true, notify_only_broken_pipelines: true, pipeline_events: true, push_events: true, tag_push_events: true, wiki_page_events: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'full')
        expect(config).to have_key('branches_to_be_notified')
        expect(config).to have_key('confidential_issues_events')
        expect(config).to have_key('confidential_note_events')
        expect(config).to have_key('issues_events')
        expect(config).to have_key('merge_requests_events')
        expect(config).to have_key('note_events')
        expect(config).to have_key('notify_only_broken_pipelines')
        expect(config).to have_key('pipeline_events')
        expect(config).to have_key('push_events')
        expect(config).to have_key('tag_push_events')
        expect(config).to have_key('wiki_page_events')
      end
    end

    context 'optional attributes' do
      it 'includes branches_to_be_notified when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('opt', required_attrs.merge(branches_to_be_notified: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'opt')
        expect(config).to have_key('branches_to_be_notified')
      end

      it 'omits branches_to_be_notified when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'minimal')
        expect(config).not_to have_key('branches_to_be_notified')
      end
      it 'includes confidential_issues_events when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('opt', required_attrs.merge(confidential_issues_events: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'opt')
        expect(config).to have_key('confidential_issues_events')
      end

      it 'omits confidential_issues_events when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'minimal')
        expect(config).not_to have_key('confidential_issues_events')
      end
      it 'includes confidential_note_events when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('opt', required_attrs.merge(confidential_note_events: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'opt')
        expect(config).to have_key('confidential_note_events')
      end

      it 'omits confidential_note_events when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'minimal')
        expect(config).not_to have_key('confidential_note_events')
      end
      it 'includes issues_events when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('opt', required_attrs.merge(issues_events: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'opt')
        expect(config).to have_key('issues_events')
      end

      it 'omits issues_events when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'minimal')
        expect(config).not_to have_key('issues_events')
      end
      it 'includes merge_requests_events when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('opt', required_attrs.merge(merge_requests_events: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'opt')
        expect(config).to have_key('merge_requests_events')
      end

      it 'omits merge_requests_events when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'minimal')
        expect(config).not_to have_key('merge_requests_events')
      end
      it 'includes note_events when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('opt', required_attrs.merge(note_events: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'opt')
        expect(config).to have_key('note_events')
      end

      it 'omits note_events when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'minimal')
        expect(config).not_to have_key('note_events')
      end
      it 'includes notify_only_broken_pipelines when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('opt', required_attrs.merge(notify_only_broken_pipelines: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'opt')
        expect(config).to have_key('notify_only_broken_pipelines')
      end

      it 'omits notify_only_broken_pipelines when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'minimal')
        expect(config).not_to have_key('notify_only_broken_pipelines')
      end
      it 'includes pipeline_events when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('opt', required_attrs.merge(pipeline_events: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'opt')
        expect(config).to have_key('pipeline_events')
      end

      it 'omits pipeline_events when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'minimal')
        expect(config).not_to have_key('pipeline_events')
      end
      it 'includes push_events when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('opt', required_attrs.merge(push_events: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'opt')
        expect(config).to have_key('push_events')
      end

      it 'omits push_events when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'minimal')
        expect(config).not_to have_key('push_events')
      end
      it 'includes tag_push_events when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('opt', required_attrs.merge(tag_push_events: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'opt')
        expect(config).to have_key('tag_push_events')
      end

      it 'omits tag_push_events when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'minimal')
        expect(config).not_to have_key('tag_push_events')
      end
      it 'includes wiki_page_events when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('opt', required_attrs.merge(wiki_page_events: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'opt')
        expect(config).to have_key('wiki_page_events')
      end

      it 'omits wiki_page_events when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'minimal')
        expect(config).not_to have_key('wiki_page_events')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts confidential_issues_events=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(confidential_issues_events: val)
          synth.gitlab_integration_microsoft_teams("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', "bool_#{val}")
          expect(config['confidential_issues_events']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts confidential_note_events=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(confidential_note_events: val)
          synth.gitlab_integration_microsoft_teams("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', "bool_#{val}")
          expect(config['confidential_note_events']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts issues_events=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(issues_events: val)
          synth.gitlab_integration_microsoft_teams("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', "bool_#{val}")
          expect(config['issues_events']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts merge_requests_events=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(merge_requests_events: val)
          synth.gitlab_integration_microsoft_teams("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', "bool_#{val}")
          expect(config['merge_requests_events']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts note_events=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(note_events: val)
          synth.gitlab_integration_microsoft_teams("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', "bool_#{val}")
          expect(config['note_events']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts notify_only_broken_pipelines=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(notify_only_broken_pipelines: val)
          synth.gitlab_integration_microsoft_teams("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', "bool_#{val}")
          expect(config['notify_only_broken_pipelines']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts pipeline_events=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(pipeline_events: val)
          synth.gitlab_integration_microsoft_teams("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', "bool_#{val}")
          expect(config['pipeline_events']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts push_events=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(push_events: val)
          synth.gitlab_integration_microsoft_teams("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', "bool_#{val}")
          expect(config['push_events']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts tag_push_events=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(tag_push_events: val)
          synth.gitlab_integration_microsoft_teams("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', "bool_#{val}")
          expect(config['tag_push_events']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts wiki_page_events=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(wiki_page_events: val)
          synth.gitlab_integration_microsoft_teams("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', "bool_#{val}")
          expect(config['wiki_page_events']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_integration_microsoft_teams', 'typed')
        expect(config['project']).to be_a(String)
        expect(config['webhook']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_microsoft_teams('first', required_attrs)
        synth.gitlab_integration_microsoft_teams('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_integration_microsoft_teams')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_integration_microsoft_teams,
    method: :gitlab_integration_microsoft_teams,
    required_attrs: { project: 'test-value', webhook: 'test-value' },
    expected_outputs: [:id, :active, :created_at, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:confidential_issues_events, :confidential_note_events, :issues_events, :merge_requests_events, :note_events, :notify_only_broken_pipelines, :pipeline_events, :push_events, :tag_push_events, :wiki_page_events]
end
