# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_pipeline_schedule resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabPipelineSchedule do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { cron: 'test-value', description: 'test-value', project: 'test-value', ref: 'test-value' } }

  describe ':gitlab_pipeline_schedule' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_pipeline_schedule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_pipeline_schedule', 'test')
        validate_required_attributes(config, [:cron, :description, :project, :ref])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_pipeline_schedule('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_pipeline_schedule)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_pipeline_schedule('test', required_attrs)

        expect(ref.id).to eq("${gitlab_pipeline_schedule.test.id}")
        expect(ref.active).to eq("${gitlab_pipeline_schedule.test.active}")
        expect(ref.cron_timezone).to eq("${gitlab_pipeline_schedule.test.cron_timezone}")
        expect(ref.owner).to eq("${gitlab_pipeline_schedule.test.owner}")
        expect(ref.pipeline_schedule_id).to eq("${gitlab_pipeline_schedule.test.pipeline_schedule_id}")
        expect(ref.take_ownership).to eq("${gitlab_pipeline_schedule.test.take_ownership}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_pipeline_schedule('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_pipeline_schedule', 'test')
        expect(config).not_to have_key('active')
        expect(config).not_to have_key('cron_timezone')
        expect(config).not_to have_key('owner')
        expect(config).not_to have_key('pipeline_schedule_id')
        expect(config).not_to have_key('take_ownership')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_pipeline_schedule('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_pipeline_schedule', 'typed')
        expect(config['cron']).to be_a(String)
        expect(config['description']).to be_a(String)
        expect(config['project']).to be_a(String)
        expect(config['ref']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_pipeline_schedule('first', required_attrs)
        synth.gitlab_pipeline_schedule('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_pipeline_schedule')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_pipeline_schedule,
    method: :gitlab_pipeline_schedule,
    required_attrs: { cron: 'test-value', description: 'test-value', project: 'test-value', ref: 'test-value' },
    expected_outputs: [:id, :active, :cron_timezone, :owner, :pipeline_schedule_id, :take_ownership],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
