# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_group_custom_attribute resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabGroupCustomAttribute do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { group: 3.14, key: 'test-value', value: 'test-value' } }

  describe ':gitlab_group_custom_attribute' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_custom_attribute('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_group_custom_attribute', 'test')
        validate_required_attributes(config, [:group, :key, :value])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_group_custom_attribute('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_group_custom_attribute)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_group_custom_attribute('test', required_attrs)

        expect(ref.id).to eq("${gitlab_group_custom_attribute.test.id}")
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_custom_attribute('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_group_custom_attribute', 'typed')
        expect(config['group']).to be_a(Float)
        expect(config['key']).to be_a(String)
        expect(config['value']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_custom_attribute('first', required_attrs)
        synth.gitlab_group_custom_attribute('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_group_custom_attribute')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_group_custom_attribute,
    method: :gitlab_group_custom_attribute,
    required_attrs: { group: 3.14, key: 'test-value', value: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
