# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_project_membership resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabProjectMembership do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { access_level: 'test-value', project: 'test-value', user_id: 3.14 } }

  describe ':gitlab_project_membership' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_membership('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_project_membership', 'test')
        validate_required_attributes(config, [:access_level, :project, :user_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_membership('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_project_membership)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_membership('test', required_attrs)

        expect(ref.id).to eq("${gitlab_project_membership.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ expires_at: 'test-value', member_role_id: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_membership('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_membership', 'full')
        expect(config).to have_key('expires_at')
        expect(config).to have_key('member_role_id')
      end
    end

    context 'optional attributes' do
      it 'includes expires_at when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_membership('opt', required_attrs.merge(expires_at: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_membership', 'opt')
        expect(config).to have_key('expires_at')
      end

      it 'omits expires_at when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_membership('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_membership', 'minimal')
        expect(config).not_to have_key('expires_at')
      end
      it 'includes member_role_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_membership('opt', required_attrs.merge(member_role_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_membership', 'opt')
        expect(config).to have_key('member_role_id')
      end

      it 'omits member_role_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_membership('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_membership', 'minimal')
        expect(config).not_to have_key('member_role_id')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_membership('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_membership', 'typed')
        expect(config['access_level']).to be_a(String)
        expect(config['project']).to be_a(String)
        expect(config['user_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_membership('first', required_attrs)
        synth.gitlab_project_membership('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_project_membership')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_project_membership,
    method: :gitlab_project_membership,
    required_attrs: { access_level: 'test-value', project: 'test-value', user_id: 3.14 },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
