# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_topic resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabTopic do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value' } }

  describe ':gitlab_topic' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_topic('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_topic', 'test')
        validate_required_attributes(config, [:name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_topic('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_topic)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_topic('test', required_attrs)

        expect(ref.id).to eq("${gitlab_topic.test.id}")
        expect(ref.avatar_hash).to eq("${gitlab_topic.test.avatar_hash}")
        expect(ref.avatar_url).to eq("${gitlab_topic.test.avatar_url}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_topic('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_topic', 'test')
        expect(config).not_to have_key('avatar_hash')
        expect(config).not_to have_key('avatar_url')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ avatar: 'test-value', description: 'test-value', soft_destroy: true, title: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_topic('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_topic', 'full')
        expect(config).to have_key('avatar')
        expect(config).to have_key('description')
        expect(config).to have_key('soft_destroy')
        expect(config).to have_key('title')
      end
    end

    context 'optional attributes' do
      it 'includes avatar when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_topic('opt', required_attrs.merge(avatar: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_topic', 'opt')
        expect(config).to have_key('avatar')
      end

      it 'omits avatar when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_topic('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_topic', 'minimal')
        expect(config).not_to have_key('avatar')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_topic('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_topic', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_topic('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_topic', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes soft_destroy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_topic('opt', required_attrs.merge(soft_destroy: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_topic', 'opt')
        expect(config).to have_key('soft_destroy')
      end

      it 'omits soft_destroy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_topic('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_topic', 'minimal')
        expect(config).not_to have_key('soft_destroy')
      end
      it 'includes title when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_topic('opt', required_attrs.merge(title: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_topic', 'opt')
        expect(config).to have_key('title')
      end

      it 'omits title when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_topic('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_topic', 'minimal')
        expect(config).not_to have_key('title')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts soft_destroy=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(soft_destroy: val)
          synth.gitlab_topic("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_topic', "bool_#{val}")
          expect(config['soft_destroy']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_topic('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_topic', 'typed')
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_topic('first', required_attrs)
        synth.gitlab_topic('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_topic')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_topic,
    method: :gitlab_topic,
    required_attrs: { name: 'test-value' },
    expected_outputs: [:id, :avatar_hash, :avatar_url],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:soft_destroy]
end
