# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_service_github resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabServiceGithub do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project: 'test-value', repository_url: 'test-value', token: 'test-value' } }

  describe ':gitlab_service_github' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_github('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_service_github', 'test')
        validate_required_attributes(config, [:project, :repository_url, :token])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_service_github('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_service_github)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_service_github('test', required_attrs)

        expect(ref.id).to eq("${gitlab_service_github.test.id}")
        expect(ref.active).to eq("${gitlab_service_github.test.active}")
        expect(ref.created_at).to eq("${gitlab_service_github.test.created_at}")
        expect(ref.title).to eq("${gitlab_service_github.test.title}")
        expect(ref.updated_at).to eq("${gitlab_service_github.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_github('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_service_github', 'test')
        expect(config).not_to have_key('active')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('title')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ static_context: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_github('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_service_github', 'full')
        expect(config).to have_key('static_context')
      end
    end

    context 'optional attributes' do
      it 'includes static_context when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_github('opt', required_attrs.merge(static_context: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_github', 'opt')
        expect(config).to have_key('static_context')
      end

      it 'omits static_context when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_github('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_github', 'minimal')
        expect(config).not_to have_key('static_context')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:token]
        expect(sensitive_fields).to include(:token)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts static_context=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(static_context: val)
          synth.gitlab_service_github("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_service_github', "bool_#{val}")
          expect(config['static_context']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_github('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_service_github', 'typed')
        expect(config['project']).to be_a(String)
        expect(config['repository_url']).to be_a(String)
        expect(config['token']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_github('first', required_attrs)
        synth.gitlab_service_github('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_service_github')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_service_github,
    method: :gitlab_service_github,
    required_attrs: { project: 'test-value', repository_url: 'test-value', token: 'test-value' },
    expected_outputs: [:id, :active, :created_at, :title, :updated_at],
    sensitive_fields: [:token],
    immutable_fields: [],
    boolean_fields: [:static_context]
end
