# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_project_level_mr_approvals resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabProjectLevelMrApprovals do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project: 'test-value' } }

  describe ':gitlab_project_level_mr_approvals' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_level_mr_approvals('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_project_level_mr_approvals', 'test')
        validate_required_attributes(config, [:project])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_level_mr_approvals('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_project_level_mr_approvals)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_level_mr_approvals('test', required_attrs)

        expect(ref.id).to eq("${gitlab_project_level_mr_approvals.test.id}")
        expect(ref.disable_overriding_approvers_per_merge_request).to eq("${gitlab_project_level_mr_approvals.test.disable_overriding_approvers_per_merge_request}")
        expect(ref.merge_requests_author_approval).to eq("${gitlab_project_level_mr_approvals.test.merge_requests_author_approval}")
        expect(ref.merge_requests_disable_committers_approval).to eq("${gitlab_project_level_mr_approvals.test.merge_requests_disable_committers_approval}")
        expect(ref.require_password_to_approve).to eq("${gitlab_project_level_mr_approvals.test.require_password_to_approve}")
        expect(ref.reset_approvals_on_push).to eq("${gitlab_project_level_mr_approvals.test.reset_approvals_on_push}")
        expect(ref.selective_code_owner_removals).to eq("${gitlab_project_level_mr_approvals.test.selective_code_owner_removals}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_level_mr_approvals('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_level_mr_approvals', 'test')
        expect(config).not_to have_key('disable_overriding_approvers_per_merge_request')
        expect(config).not_to have_key('merge_requests_author_approval')
        expect(config).not_to have_key('merge_requests_disable_committers_approval')
        expect(config).not_to have_key('require_password_to_approve')
        expect(config).not_to have_key('reset_approvals_on_push')
        expect(config).not_to have_key('selective_code_owner_removals')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_level_mr_approvals('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_level_mr_approvals', 'typed')
        expect(config['project']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_level_mr_approvals('first', required_attrs)
        synth.gitlab_project_level_mr_approvals('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_project_level_mr_approvals')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_project_level_mr_approvals,
    method: :gitlab_project_level_mr_approvals,
    required_attrs: { project: 'test-value' },
    expected_outputs: [:id, :disable_overriding_approvers_per_merge_request, :merge_requests_author_approval, :merge_requests_disable_committers_approval, :require_password_to_approve, :reset_approvals_on_push, :selective_code_owner_removals],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
