# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_project_badge resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabProjectBadge do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { image_url: 'test-value', link_url: 'test-value', project: 'test-value' } }

  describe ':gitlab_project_badge' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_badge('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_project_badge', 'test')
        validate_required_attributes(config, [:image_url, :link_url, :project])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_badge('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_project_badge)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_badge('test', required_attrs)

        expect(ref.id).to eq("${gitlab_project_badge.test.id}")
        expect(ref.rendered_image_url).to eq("${gitlab_project_badge.test.rendered_image_url}")
        expect(ref.rendered_link_url).to eq("${gitlab_project_badge.test.rendered_link_url}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_badge('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_badge', 'test')
        expect(config).not_to have_key('rendered_image_url')
        expect(config).not_to have_key('rendered_link_url')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ name: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_badge('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_badge', 'full')
        expect(config).to have_key('name')
      end
    end

    context 'optional attributes' do
      it 'includes name when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_badge('opt', required_attrs.merge(name: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_badge', 'opt')
        expect(config).to have_key('name')
      end

      it 'omits name when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_badge('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_badge', 'minimal')
        expect(config).not_to have_key('name')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_badge('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_badge', 'typed')
        expect(config['image_url']).to be_a(String)
        expect(config['link_url']).to be_a(String)
        expect(config['project']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_badge('first', required_attrs)
        synth.gitlab_project_badge('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_project_badge')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_project_badge,
    method: :gitlab_project_badge,
    required_attrs: { image_url: 'test-value', link_url: 'test-value', project: 'test-value' },
    expected_outputs: [:id, :rendered_image_url, :rendered_link_url],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
