# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_user_runner resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabUserRunner do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { runner_type: 'test-value' } }

  describe ':gitlab_user_runner' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user_runner('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_user_runner', 'test')
        validate_required_attributes(config, [:runner_type])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_user_runner('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_user_runner)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_user_runner('test', required_attrs)

        expect(ref.id).to eq("${gitlab_user_runner.test.id}")
        expect(ref.access_level).to eq("${gitlab_user_runner.test.access_level}")
        expect(ref.description).to eq("${gitlab_user_runner.test.description}")
        expect(ref.locked).to eq("${gitlab_user_runner.test.locked}")
        expect(ref.maintenance_note).to eq("${gitlab_user_runner.test.maintenance_note}")
        expect(ref.maximum_timeout).to eq("${gitlab_user_runner.test.maximum_timeout}")
        expect(ref.paused).to eq("${gitlab_user_runner.test.paused}")
        expect(ref.tag_list).to eq("${gitlab_user_runner.test.tag_list}")
        expect(ref.token).to eq("${gitlab_user_runner.test.token}")
        expect(ref.untagged).to eq("${gitlab_user_runner.test.untagged}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user_runner('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_user_runner', 'test')
        expect(config).not_to have_key('access_level')
        expect(config).not_to have_key('description')
        expect(config).not_to have_key('locked')
        expect(config).not_to have_key('maintenance_note')
        expect(config).not_to have_key('maximum_timeout')
        expect(config).not_to have_key('paused')
        expect(config).not_to have_key('tag_list')
        expect(config).not_to have_key('token')
        expect(config).not_to have_key('untagged')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ group_id: 3.14, project_id: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user_runner('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_user_runner', 'full')
        expect(config).to have_key('group_id')
        expect(config).to have_key('project_id')
      end
    end

    context 'optional attributes' do
      it 'includes group_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user_runner('opt', required_attrs.merge(group_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user_runner', 'opt')
        expect(config).to have_key('group_id')
      end

      it 'omits group_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user_runner('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user_runner', 'minimal')
        expect(config).not_to have_key('group_id')
      end
      it 'includes project_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user_runner('opt', required_attrs.merge(project_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user_runner', 'opt')
        expect(config).to have_key('project_id')
      end

      it 'omits project_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user_runner('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user_runner', 'minimal')
        expect(config).not_to have_key('project_id')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:token]
        expect(sensitive_fields).to include(:token)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user_runner('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_user_runner', 'typed')
        expect(config['runner_type']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user_runner('first', required_attrs)
        synth.gitlab_user_runner('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_user_runner')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_user_runner,
    method: :gitlab_user_runner,
    required_attrs: { runner_type: 'test-value' },
    expected_outputs: [:id, :access_level, :description, :locked, :maintenance_note, :maximum_timeout, :paused, :tag_list, :token, :untagged],
    sensitive_fields: [:token],
    immutable_fields: [],
    boolean_fields: []
end
