# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_global_level_notifications resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabGlobalLevelNotifications do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':gitlab_global_level_notifications' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_global_level_notifications('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_global_level_notifications', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_global_level_notifications('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_global_level_notifications)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_global_level_notifications('test', required_attrs)

        expect(ref.id).to eq("${gitlab_global_level_notifications.test.id}")
        expect(ref.close_issue).to eq("${gitlab_global_level_notifications.test.close_issue}")
        expect(ref.close_merge_request).to eq("${gitlab_global_level_notifications.test.close_merge_request}")
        expect(ref.failed_pipeline).to eq("${gitlab_global_level_notifications.test.failed_pipeline}")
        expect(ref.fixed_pipeline).to eq("${gitlab_global_level_notifications.test.fixed_pipeline}")
        expect(ref.issue_due).to eq("${gitlab_global_level_notifications.test.issue_due}")
        expect(ref.level).to eq("${gitlab_global_level_notifications.test.level}")
        expect(ref.merge_merge_request).to eq("${gitlab_global_level_notifications.test.merge_merge_request}")
        expect(ref.merge_when_pipeline_succeeds).to eq("${gitlab_global_level_notifications.test.merge_when_pipeline_succeeds}")
        expect(ref.moved_project).to eq("${gitlab_global_level_notifications.test.moved_project}")
        expect(ref.new_issue).to eq("${gitlab_global_level_notifications.test.new_issue}")
        expect(ref.new_merge_request).to eq("${gitlab_global_level_notifications.test.new_merge_request}")
        expect(ref.new_note).to eq("${gitlab_global_level_notifications.test.new_note}")
        expect(ref.push_to_merge_request).to eq("${gitlab_global_level_notifications.test.push_to_merge_request}")
        expect(ref.reassign_issue).to eq("${gitlab_global_level_notifications.test.reassign_issue}")
        expect(ref.reassign_merge_request).to eq("${gitlab_global_level_notifications.test.reassign_merge_request}")
        expect(ref.reopen_issue).to eq("${gitlab_global_level_notifications.test.reopen_issue}")
        expect(ref.reopen_merge_request).to eq("${gitlab_global_level_notifications.test.reopen_merge_request}")
        expect(ref.success_pipeline).to eq("${gitlab_global_level_notifications.test.success_pipeline}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_global_level_notifications('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_global_level_notifications', 'test')
        expect(config).not_to have_key('close_issue')
        expect(config).not_to have_key('close_merge_request')
        expect(config).not_to have_key('failed_pipeline')
        expect(config).not_to have_key('fixed_pipeline')
        expect(config).not_to have_key('issue_due')
        expect(config).not_to have_key('level')
        expect(config).not_to have_key('merge_merge_request')
        expect(config).not_to have_key('merge_when_pipeline_succeeds')
        expect(config).not_to have_key('moved_project')
        expect(config).not_to have_key('new_issue')
        expect(config).not_to have_key('new_merge_request')
        expect(config).not_to have_key('new_note')
        expect(config).not_to have_key('push_to_merge_request')
        expect(config).not_to have_key('reassign_issue')
        expect(config).not_to have_key('reassign_merge_request')
        expect(config).not_to have_key('reopen_issue')
        expect(config).not_to have_key('reopen_merge_request')
        expect(config).not_to have_key('success_pipeline')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_global_level_notifications('first', required_attrs)
        synth.gitlab_global_level_notifications('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_global_level_notifications')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_global_level_notifications,
    method: :gitlab_global_level_notifications,
    required_attrs: {},
    expected_outputs: [:id, :close_issue, :close_merge_request, :failed_pipeline, :fixed_pipeline, :issue_due, :level, :merge_merge_request, :merge_when_pipeline_succeeds, :moved_project, :new_issue, :new_merge_request, :new_note, :push_to_merge_request, :reassign_issue, :reassign_merge_request, :reopen_issue, :reopen_merge_request, :success_pipeline],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
