# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_group_cluster resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabGroupCluster do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { group: 'test-value', kubernetes_api_url: 'test-value', kubernetes_token: 'test-value', name: 'test-value' } }

  describe ':gitlab_group_cluster' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_group_cluster', 'test')
        validate_required_attributes(config, [:group, :kubernetes_api_url, :kubernetes_token, :name])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_group_cluster('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_group_cluster)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_group_cluster('test', required_attrs)

        expect(ref.id).to eq("${gitlab_group_cluster.test.id}")
        expect(ref.cluster_type).to eq("${gitlab_group_cluster.test.cluster_type}")
        expect(ref.created_at).to eq("${gitlab_group_cluster.test.created_at}")
        expect(ref.platform_type).to eq("${gitlab_group_cluster.test.platform_type}")
        expect(ref.provider_type).to eq("${gitlab_group_cluster.test.provider_type}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_group_cluster', 'test')
        expect(config).not_to have_key('cluster_type')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('platform_type')
        expect(config).not_to have_key('provider_type')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ domain: 'test-value', enabled: true, environment_scope: 'test-value', kubernetes_authorization_type: 'test-value', kubernetes_ca_cert: 'test-value', managed: true, management_project_id: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_group_cluster', 'full')
        expect(config).to have_key('domain')
        expect(config).to have_key('enabled')
        expect(config).to have_key('environment_scope')
        expect(config).to have_key('kubernetes_authorization_type')
        expect(config).to have_key('kubernetes_ca_cert')
        expect(config).to have_key('managed')
        expect(config).to have_key('management_project_id')
      end
    end

    context 'optional attributes' do
      it 'includes domain when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('opt', required_attrs.merge(domain: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group_cluster', 'opt')
        expect(config).to have_key('domain')
      end

      it 'omits domain when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group_cluster', 'minimal')
        expect(config).not_to have_key('domain')
      end
      it 'includes enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('opt', required_attrs.merge(enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group_cluster', 'opt')
        expect(config).to have_key('enabled')
      end

      it 'omits enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group_cluster', 'minimal')
        expect(config).not_to have_key('enabled')
      end
      it 'includes environment_scope when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('opt', required_attrs.merge(environment_scope: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group_cluster', 'opt')
        expect(config).to have_key('environment_scope')
      end

      it 'omits environment_scope when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group_cluster', 'minimal')
        expect(config).not_to have_key('environment_scope')
      end
      it 'includes kubernetes_authorization_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('opt', required_attrs.merge(kubernetes_authorization_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group_cluster', 'opt')
        expect(config).to have_key('kubernetes_authorization_type')
      end

      it 'omits kubernetes_authorization_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group_cluster', 'minimal')
        expect(config).not_to have_key('kubernetes_authorization_type')
      end
      it 'includes kubernetes_ca_cert when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('opt', required_attrs.merge(kubernetes_ca_cert: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group_cluster', 'opt')
        expect(config).to have_key('kubernetes_ca_cert')
      end

      it 'omits kubernetes_ca_cert when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group_cluster', 'minimal')
        expect(config).not_to have_key('kubernetes_ca_cert')
      end
      it 'includes managed when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('opt', required_attrs.merge(managed: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group_cluster', 'opt')
        expect(config).to have_key('managed')
      end

      it 'omits managed when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group_cluster', 'minimal')
        expect(config).not_to have_key('managed')
      end
      it 'includes management_project_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('opt', required_attrs.merge(management_project_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group_cluster', 'opt')
        expect(config).to have_key('management_project_id')
      end

      it 'omits management_project_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group_cluster', 'minimal')
        expect(config).not_to have_key('management_project_id')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:kubernetes_token]
        expect(sensitive_fields).to include(:kubernetes_token)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(enabled: val)
          synth.gitlab_group_cluster("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_group_cluster', "bool_#{val}")
          expect(config['enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts managed=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(managed: val)
          synth.gitlab_group_cluster("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_group_cluster', "bool_#{val}")
          expect(config['managed']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_group_cluster', 'typed')
        expect(config['group']).to be_a(String)
        expect(config['kubernetes_api_url']).to be_a(String)
        expect(config['kubernetes_token']).to be_a(String)
        expect(config['name']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group_cluster('first', required_attrs)
        synth.gitlab_group_cluster('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_group_cluster')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_group_cluster,
    method: :gitlab_group_cluster,
    required_attrs: { group: 'test-value', kubernetes_api_url: 'test-value', kubernetes_token: 'test-value', name: 'test-value' },
    expected_outputs: [:id, :cluster_type, :created_at, :platform_type, :provider_type],
    sensitive_fields: [:kubernetes_token],
    immutable_fields: [],
    boolean_fields: [:enabled, :managed]
end
