# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_integration_external_wiki resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabIntegrationExternalWiki do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { external_wiki_url: 'test-value', project: 'test-value' } }

  describe ':gitlab_integration_external_wiki' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_external_wiki('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_integration_external_wiki', 'test')
        validate_required_attributes(config, [:external_wiki_url, :project])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_integration_external_wiki('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_integration_external_wiki)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_integration_external_wiki('test', required_attrs)

        expect(ref.id).to eq("${gitlab_integration_external_wiki.test.id}")
        expect(ref.active).to eq("${gitlab_integration_external_wiki.test.active}")
        expect(ref.created_at).to eq("${gitlab_integration_external_wiki.test.created_at}")
        expect(ref.slug).to eq("${gitlab_integration_external_wiki.test.slug}")
        expect(ref.title).to eq("${gitlab_integration_external_wiki.test.title}")
        expect(ref.updated_at).to eq("${gitlab_integration_external_wiki.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_external_wiki('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_integration_external_wiki', 'test')
        expect(config).not_to have_key('active')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('slug')
        expect(config).not_to have_key('title')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_external_wiki('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_integration_external_wiki', 'typed')
        expect(config['external_wiki_url']).to be_a(String)
        expect(config['project']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_external_wiki('first', required_attrs)
        synth.gitlab_integration_external_wiki('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_integration_external_wiki')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_integration_external_wiki,
    method: :gitlab_integration_external_wiki,
    required_attrs: { external_wiki_url: 'test-value', project: 'test-value' },
    expected_outputs: [:id, :active, :created_at, :slug, :title, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
