# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_integration_harbor resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabIntegrationHarbor do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { password: 'test-value', project: 'test-value', project_name: 'test-value', url: 'test-value', username: 'test-value' } }

  describe ':gitlab_integration_harbor' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_harbor('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_integration_harbor', 'test')
        validate_required_attributes(config, [:password, :project, :project_name, :url, :username])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_integration_harbor('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_integration_harbor)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_integration_harbor('test', required_attrs)

        expect(ref.id).to eq("${gitlab_integration_harbor.test.id}")
        expect(ref.active).to eq("${gitlab_integration_harbor.test.active}")
        expect(ref.use_inherited_settings).to eq("${gitlab_integration_harbor.test.use_inherited_settings}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_harbor('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_integration_harbor', 'test')
        expect(config).not_to have_key('active')
        expect(config).not_to have_key('use_inherited_settings')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:password]
        expect(sensitive_fields).to include(:password)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_harbor('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_integration_harbor', 'typed')
        expect(config['password']).to be_a(String)
        expect(config['project']).to be_a(String)
        expect(config['project_name']).to be_a(String)
        expect(config['url']).to be_a(String)
        expect(config['username']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_harbor('first', required_attrs)
        synth.gitlab_integration_harbor('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_integration_harbor')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_integration_harbor,
    method: :gitlab_integration_harbor,
    required_attrs: { password: 'test-value', project: 'test-value', project_name: 'test-value', url: 'test-value', username: 'test-value' },
    expected_outputs: [:id, :active, :use_inherited_settings],
    sensitive_fields: [:password],
    immutable_fields: [],
    boolean_fields: []
end
