# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_user_sshkey resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabUserSshkey do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { key: 'test-value', title: 'test-value' } }

  describe ':gitlab_user_sshkey' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user_sshkey('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_user_sshkey', 'test')
        validate_required_attributes(config, [:key, :title])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_user_sshkey('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_user_sshkey)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_user_sshkey('test', required_attrs)

        expect(ref.id).to eq("${gitlab_user_sshkey.test.id}")
        expect(ref.created_at).to eq("${gitlab_user_sshkey.test.created_at}")
        expect(ref.key_id).to eq("${gitlab_user_sshkey.test.key_id}")
        expect(ref.user_id).to eq("${gitlab_user_sshkey.test.user_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user_sshkey('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_user_sshkey', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('key_id')
        expect(config).not_to have_key('user_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ expires_at: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user_sshkey('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_user_sshkey', 'full')
        expect(config).to have_key('expires_at')
      end
    end

    context 'optional attributes' do
      it 'includes expires_at when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user_sshkey('opt', required_attrs.merge(expires_at: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user_sshkey', 'opt')
        expect(config).to have_key('expires_at')
      end

      it 'omits expires_at when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user_sshkey('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user_sshkey', 'minimal')
        expect(config).not_to have_key('expires_at')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user_sshkey('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_user_sshkey', 'typed')
        expect(config['key']).to be_a(String)
        expect(config['title']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user_sshkey('first', required_attrs)
        synth.gitlab_user_sshkey('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_user_sshkey')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_user_sshkey,
    method: :gitlab_user_sshkey,
    required_attrs: { key: 'test-value', title: 'test-value' },
    expected_outputs: [:id, :created_at, :key_id, :user_id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
