# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_branch resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabBranch do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', project: 'test-value', ref: 'test-value' } }

  describe ':gitlab_branch' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_branch('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_branch', 'test')
        validate_required_attributes(config, [:name, :project, :ref])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_branch('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_branch)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_branch('test', required_attrs)

        expect(ref.id).to eq("${gitlab_branch.test.id}")
        expect(ref.can_push).to eq("${gitlab_branch.test.can_push}")
        expect(ref.commit).to eq("${gitlab_branch.test.commit}")
        expect(ref.default).to eq("${gitlab_branch.test.default}")
        expect(ref.developer_can_merge).to eq("${gitlab_branch.test.developer_can_merge}")
        expect(ref.developer_can_push).to eq("${gitlab_branch.test.developer_can_push}")
        expect(ref.merged).to eq("${gitlab_branch.test.merged}")
        expect(ref.protected).to eq("${gitlab_branch.test.protected}")
        expect(ref.web_url).to eq("${gitlab_branch.test.web_url}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_branch('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_branch', 'test')
        expect(config).not_to have_key('can_push')
        expect(config).not_to have_key('commit')
        expect(config).not_to have_key('default')
        expect(config).not_to have_key('developer_can_merge')
        expect(config).not_to have_key('developer_can_push')
        expect(config).not_to have_key('merged')
        expect(config).not_to have_key('protected')
        expect(config).not_to have_key('web_url')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ keep_on_destroy: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_branch('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_branch', 'full')
        expect(config).to have_key('keep_on_destroy')
      end
    end

    context 'optional attributes' do
      it 'includes keep_on_destroy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_branch('opt', required_attrs.merge(keep_on_destroy: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_branch', 'opt')
        expect(config).to have_key('keep_on_destroy')
      end

      it 'omits keep_on_destroy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_branch('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_branch', 'minimal')
        expect(config).not_to have_key('keep_on_destroy')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts keep_on_destroy=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(keep_on_destroy: val)
          synth.gitlab_branch("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_branch', "bool_#{val}")
          expect(config['keep_on_destroy']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_branch('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_branch', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['project']).to be_a(String)
        expect(config['ref']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_branch('first', required_attrs)
        synth.gitlab_branch('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_branch')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_branch,
    method: :gitlab_branch,
    required_attrs: { name: 'test-value', project: 'test-value', ref: 'test-value' },
    expected_outputs: [:id, :can_push, :commit, :default, :developer_can_merge, :developer_can_push, :merged, :protected, :web_url],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:keep_on_destroy]
end
