# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_service_slack resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabServiceSlack do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project: 'test-value', webhook: 'test-value' } }

  describe ':gitlab_service_slack' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'test')
        validate_required_attributes(config, [:project, :webhook])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_service_slack('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_service_slack)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_service_slack('test', required_attrs)

        expect(ref.id).to eq("${gitlab_service_slack.test.id}")
        expect(ref.branches_to_be_notified).to eq("${gitlab_service_slack.test.branches_to_be_notified}")
        expect(ref.confidential_issues_events).to eq("${gitlab_service_slack.test.confidential_issues_events}")
        expect(ref.confidential_note_channel).to eq("${gitlab_service_slack.test.confidential_note_channel}")
        expect(ref.confidential_note_events).to eq("${gitlab_service_slack.test.confidential_note_events}")
        expect(ref.issues_events).to eq("${gitlab_service_slack.test.issues_events}")
        expect(ref.job_events).to eq("${gitlab_service_slack.test.job_events}")
        expect(ref.merge_requests_events).to eq("${gitlab_service_slack.test.merge_requests_events}")
        expect(ref.note_events).to eq("${gitlab_service_slack.test.note_events}")
        expect(ref.notify_only_broken_pipelines).to eq("${gitlab_service_slack.test.notify_only_broken_pipelines}")
        expect(ref.notify_only_default_branch).to eq("${gitlab_service_slack.test.notify_only_default_branch}")
        expect(ref.pipeline_events).to eq("${gitlab_service_slack.test.pipeline_events}")
        expect(ref.push_events).to eq("${gitlab_service_slack.test.push_events}")
        expect(ref.tag_push_events).to eq("${gitlab_service_slack.test.tag_push_events}")
        expect(ref.wiki_page_events).to eq("${gitlab_service_slack.test.wiki_page_events}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_service_slack', 'test')
        expect(config).not_to have_key('branches_to_be_notified')
        expect(config).not_to have_key('confidential_issues_events')
        expect(config).not_to have_key('confidential_note_channel')
        expect(config).not_to have_key('confidential_note_events')
        expect(config).not_to have_key('issues_events')
        expect(config).not_to have_key('job_events')
        expect(config).not_to have_key('merge_requests_events')
        expect(config).not_to have_key('note_events')
        expect(config).not_to have_key('notify_only_broken_pipelines')
        expect(config).not_to have_key('notify_only_default_branch')
        expect(config).not_to have_key('pipeline_events')
        expect(config).not_to have_key('push_events')
        expect(config).not_to have_key('tag_push_events')
        expect(config).not_to have_key('wiki_page_events')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ confidential_issue_channel: 'test-value', issue_channel: 'test-value', merge_request_channel: 'test-value', note_channel: 'test-value', pipeline_channel: 'test-value', push_channel: 'test-value', tag_push_channel: 'test-value', username: 'test-value', wiki_page_channel: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_service_slack', 'full')
        expect(config).to have_key('confidential_issue_channel')
        expect(config).to have_key('issue_channel')
        expect(config).to have_key('merge_request_channel')
        expect(config).to have_key('note_channel')
        expect(config).to have_key('pipeline_channel')
        expect(config).to have_key('push_channel')
        expect(config).to have_key('tag_push_channel')
        expect(config).to have_key('username')
        expect(config).to have_key('wiki_page_channel')
      end
    end

    context 'optional attributes' do
      it 'includes confidential_issue_channel when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('opt', required_attrs.merge(confidential_issue_channel: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'opt')
        expect(config).to have_key('confidential_issue_channel')
      end

      it 'omits confidential_issue_channel when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'minimal')
        expect(config).not_to have_key('confidential_issue_channel')
      end
      it 'includes issue_channel when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('opt', required_attrs.merge(issue_channel: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'opt')
        expect(config).to have_key('issue_channel')
      end

      it 'omits issue_channel when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'minimal')
        expect(config).not_to have_key('issue_channel')
      end
      it 'includes merge_request_channel when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('opt', required_attrs.merge(merge_request_channel: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'opt')
        expect(config).to have_key('merge_request_channel')
      end

      it 'omits merge_request_channel when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'minimal')
        expect(config).not_to have_key('merge_request_channel')
      end
      it 'includes note_channel when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('opt', required_attrs.merge(note_channel: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'opt')
        expect(config).to have_key('note_channel')
      end

      it 'omits note_channel when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'minimal')
        expect(config).not_to have_key('note_channel')
      end
      it 'includes pipeline_channel when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('opt', required_attrs.merge(pipeline_channel: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'opt')
        expect(config).to have_key('pipeline_channel')
      end

      it 'omits pipeline_channel when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'minimal')
        expect(config).not_to have_key('pipeline_channel')
      end
      it 'includes push_channel when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('opt', required_attrs.merge(push_channel: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'opt')
        expect(config).to have_key('push_channel')
      end

      it 'omits push_channel when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'minimal')
        expect(config).not_to have_key('push_channel')
      end
      it 'includes tag_push_channel when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('opt', required_attrs.merge(tag_push_channel: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'opt')
        expect(config).to have_key('tag_push_channel')
      end

      it 'omits tag_push_channel when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'minimal')
        expect(config).not_to have_key('tag_push_channel')
      end
      it 'includes username when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('opt', required_attrs.merge(username: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'opt')
        expect(config).to have_key('username')
      end

      it 'omits username when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'minimal')
        expect(config).not_to have_key('username')
      end
      it 'includes wiki_page_channel when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('opt', required_attrs.merge(wiki_page_channel: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'opt')
        expect(config).to have_key('wiki_page_channel')
      end

      it 'omits wiki_page_channel when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_slack', 'minimal')
        expect(config).not_to have_key('wiki_page_channel')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_service_slack', 'typed')
        expect(config['project']).to be_a(String)
        expect(config['webhook']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_slack('first', required_attrs)
        synth.gitlab_service_slack('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_service_slack')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_service_slack,
    method: :gitlab_service_slack,
    required_attrs: { project: 'test-value', webhook: 'test-value' },
    expected_outputs: [:id, :branches_to_be_notified, :confidential_issues_events, :confidential_note_channel, :confidential_note_events, :issues_events, :job_events, :merge_requests_events, :note_events, :notify_only_broken_pipelines, :notify_only_default_branch, :pipeline_events, :push_events, :tag_push_events, :wiki_page_events],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
