# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_value_stream_analytics resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabValueStreamAnalytics do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', stages: [{ 'key1' => 'val1' }] } }

  describe ':gitlab_value_stream_analytics' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_value_stream_analytics('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_value_stream_analytics', 'test')
        validate_required_attributes(config, [:name, :stages])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_value_stream_analytics('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_value_stream_analytics)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_value_stream_analytics('test', required_attrs)

        expect(ref.id).to eq("${gitlab_value_stream_analytics.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ group_full_path: 'test-value', project_full_path: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_value_stream_analytics('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_value_stream_analytics', 'full')
        expect(config).to have_key('group_full_path')
        expect(config).to have_key('project_full_path')
      end
    end

    context 'optional attributes' do
      it 'includes group_full_path when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_value_stream_analytics('opt', required_attrs.merge(group_full_path: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_value_stream_analytics', 'opt')
        expect(config).to have_key('group_full_path')
      end

      it 'omits group_full_path when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_value_stream_analytics('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_value_stream_analytics', 'minimal')
        expect(config).not_to have_key('group_full_path')
      end
      it 'includes project_full_path when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_value_stream_analytics('opt', required_attrs.merge(project_full_path: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_value_stream_analytics', 'opt')
        expect(config).to have_key('project_full_path')
      end

      it 'omits project_full_path when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_value_stream_analytics('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_value_stream_analytics', 'minimal')
        expect(config).not_to have_key('project_full_path')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_value_stream_analytics('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_value_stream_analytics', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['stages']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_value_stream_analytics('first', required_attrs)
        synth.gitlab_value_stream_analytics('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_value_stream_analytics')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_value_stream_analytics,
    method: :gitlab_value_stream_analytics,
    required_attrs: { name: 'test-value', stages: [{ 'key1' => 'val1' }] },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
