# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_user resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabUser do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { email: 'test-value', name: 'test-value', username: 'test-value' } }

  describe ':gitlab_user' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_user', 'test')
        validate_required_attributes(config, [:email, :name, :username])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_user('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_user)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_user('test', required_attrs)

        expect(ref.id).to eq("${gitlab_user.test.id}")
        expect(ref.namespace_id).to eq("${gitlab_user.test.namespace_id}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_user', 'test')
        expect(config).not_to have_key('namespace_id')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ can_create_group: true, extern_uid: 'test-value', external_provider: 'test-value', force_random_password: true, is_admin: true, is_external: true, note: 'test-value', password: 'test-value', projects_limit: 3.14, reset_password: true, skip_confirmation: true, state: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_user', 'full')
        expect(config).to have_key('can_create_group')
        expect(config).to have_key('extern_uid')
        expect(config).to have_key('external_provider')
        expect(config).to have_key('force_random_password')
        expect(config).to have_key('is_admin')
        expect(config).to have_key('is_external')
        expect(config).to have_key('note')
        expect(config).to have_key('password')
        expect(config).to have_key('projects_limit')
        expect(config).to have_key('reset_password')
        expect(config).to have_key('skip_confirmation')
        expect(config).to have_key('state')
      end
    end

    context 'optional attributes' do
      it 'includes can_create_group when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('opt', required_attrs.merge(can_create_group: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'opt')
        expect(config).to have_key('can_create_group')
      end

      it 'omits can_create_group when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'minimal')
        expect(config).not_to have_key('can_create_group')
      end
      it 'includes extern_uid when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('opt', required_attrs.merge(extern_uid: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'opt')
        expect(config).to have_key('extern_uid')
      end

      it 'omits extern_uid when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'minimal')
        expect(config).not_to have_key('extern_uid')
      end
      it 'includes external_provider when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('opt', required_attrs.merge(external_provider: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'opt')
        expect(config).to have_key('external_provider')
      end

      it 'omits external_provider when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'minimal')
        expect(config).not_to have_key('external_provider')
      end
      it 'includes force_random_password when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('opt', required_attrs.merge(force_random_password: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'opt')
        expect(config).to have_key('force_random_password')
      end

      it 'omits force_random_password when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'minimal')
        expect(config).not_to have_key('force_random_password')
      end
      it 'includes is_admin when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('opt', required_attrs.merge(is_admin: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'opt')
        expect(config).to have_key('is_admin')
      end

      it 'omits is_admin when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'minimal')
        expect(config).not_to have_key('is_admin')
      end
      it 'includes is_external when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('opt', required_attrs.merge(is_external: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'opt')
        expect(config).to have_key('is_external')
      end

      it 'omits is_external when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'minimal')
        expect(config).not_to have_key('is_external')
      end
      it 'includes note when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('opt', required_attrs.merge(note: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'opt')
        expect(config).to have_key('note')
      end

      it 'omits note when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'minimal')
        expect(config).not_to have_key('note')
      end
      it 'includes password when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('opt', required_attrs.merge(password: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'opt')
        expect(config).to have_key('password')
      end

      it 'omits password when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'minimal')
        expect(config).not_to have_key('password')
      end
      it 'includes projects_limit when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('opt', required_attrs.merge(projects_limit: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'opt')
        expect(config).to have_key('projects_limit')
      end

      it 'omits projects_limit when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'minimal')
        expect(config).not_to have_key('projects_limit')
      end
      it 'includes reset_password when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('opt', required_attrs.merge(reset_password: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'opt')
        expect(config).to have_key('reset_password')
      end

      it 'omits reset_password when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'minimal')
        expect(config).not_to have_key('reset_password')
      end
      it 'includes skip_confirmation when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('opt', required_attrs.merge(skip_confirmation: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'opt')
        expect(config).to have_key('skip_confirmation')
      end

      it 'omits skip_confirmation when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'minimal')
        expect(config).not_to have_key('skip_confirmation')
      end
      it 'includes state when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('opt', required_attrs.merge(state: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'opt')
        expect(config).to have_key('state')
      end

      it 'omits state when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_user', 'minimal')
        expect(config).not_to have_key('state')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:password]
        expect(sensitive_fields).to include(:password)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts can_create_group=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(can_create_group: val)
          synth.gitlab_user("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_user', "bool_#{val}")
          expect(config['can_create_group']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts force_random_password=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(force_random_password: val)
          synth.gitlab_user("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_user', "bool_#{val}")
          expect(config['force_random_password']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts is_admin=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_admin: val)
          synth.gitlab_user("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_user', "bool_#{val}")
          expect(config['is_admin']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts is_external=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(is_external: val)
          synth.gitlab_user("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_user', "bool_#{val}")
          expect(config['is_external']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts reset_password=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(reset_password: val)
          synth.gitlab_user("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_user', "bool_#{val}")
          expect(config['reset_password']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts skip_confirmation=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(skip_confirmation: val)
          synth.gitlab_user("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_user', "bool_#{val}")
          expect(config['skip_confirmation']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_user', 'typed')
        expect(config['email']).to be_a(String)
        expect(config['name']).to be_a(String)
        expect(config['username']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_user('first', required_attrs)
        synth.gitlab_user('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_user')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_user,
    method: :gitlab_user,
    required_attrs: { email: 'test-value', name: 'test-value', username: 'test-value' },
    expected_outputs: [:id, :namespace_id],
    sensitive_fields: [:password],
    immutable_fields: [],
    boolean_fields: [:can_create_group, :force_random_password, :is_admin, :is_external, :reset_password, :skip_confirmation]
end
