# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_project_issue_board resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabProjectIssueBoard do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', project: 'test-value' } }

  describe ':gitlab_project_issue_board' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue_board('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_project_issue_board', 'test')
        validate_required_attributes(config, [:name, :project])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_issue_board('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_project_issue_board)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_issue_board('test', required_attrs)

        expect(ref.id).to eq("${gitlab_project_issue_board.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ assignee_id: 3.14, labels: ['test-value'], lists: [{ 'key1' => 'val1' }], milestone_id: 3.14, weight: 3.14 }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue_board('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_issue_board', 'full')
        expect(config).to have_key('assignee_id')
        expect(config).to have_key('labels')
        expect(config).to have_key('lists')
        expect(config).to have_key('milestone_id')
        expect(config).to have_key('weight')
      end
    end

    context 'optional attributes' do
      it 'includes assignee_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue_board('opt', required_attrs.merge(assignee_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue_board', 'opt')
        expect(config).to have_key('assignee_id')
      end

      it 'omits assignee_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue_board('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue_board', 'minimal')
        expect(config).not_to have_key('assignee_id')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue_board('opt', required_attrs.merge(labels: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue_board', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue_board('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue_board', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes lists when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue_board('opt', required_attrs.merge(lists: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue_board', 'opt')
        expect(config).to have_key('lists')
      end

      it 'omits lists when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue_board('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue_board', 'minimal')
        expect(config).not_to have_key('lists')
      end
      it 'includes milestone_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue_board('opt', required_attrs.merge(milestone_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue_board', 'opt')
        expect(config).to have_key('milestone_id')
      end

      it 'omits milestone_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue_board('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue_board', 'minimal')
        expect(config).not_to have_key('milestone_id')
      end
      it 'includes weight when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue_board('opt', required_attrs.merge(weight: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue_board', 'opt')
        expect(config).to have_key('weight')
      end

      it 'omits weight when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue_board('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue_board', 'minimal')
        expect(config).not_to have_key('weight')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue_board('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_issue_board', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['project']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue_board('first', required_attrs)
        synth.gitlab_project_issue_board('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_project_issue_board')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_project_issue_board,
    method: :gitlab_project_issue_board,
    required_attrs: { name: 'test-value', project: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
