# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_service_jira resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabServiceJira do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { password: 'test-value', project: 'test-value', url: 'test-value' } }

  describe ':gitlab_service_jira' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'test')
        validate_required_attributes(config, [:password, :project, :url])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_service_jira('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_service_jira)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_service_jira('test', required_attrs)

        expect(ref.id).to eq("${gitlab_service_jira.test.id}")
        expect(ref.active).to eq("${gitlab_service_jira.test.active}")
        expect(ref.api_url).to eq("${gitlab_service_jira.test.api_url}")
        expect(ref.comment_on_event_enabled).to eq("${gitlab_service_jira.test.comment_on_event_enabled}")
        expect(ref.commit_events).to eq("${gitlab_service_jira.test.commit_events}")
        expect(ref.created_at).to eq("${gitlab_service_jira.test.created_at}")
        expect(ref.merge_requests_events).to eq("${gitlab_service_jira.test.merge_requests_events}")
        expect(ref.title).to eq("${gitlab_service_jira.test.title}")
        expect(ref.updated_at).to eq("${gitlab_service_jira.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_service_jira', 'test')
        expect(config).not_to have_key('active')
        expect(config).not_to have_key('api_url')
        expect(config).not_to have_key('comment_on_event_enabled')
        expect(config).not_to have_key('commit_events')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('merge_requests_events')
        expect(config).not_to have_key('title')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ issues_enabled: true, jira_auth_type: 3.14, jira_issue_prefix: 'test-value', jira_issue_regex: 'test-value', jira_issue_transition_automatic: true, jira_issue_transition_id: 'test-value', project_key: 'test-value', project_keys: ['test-value'], use_inherited_settings: true, username: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_service_jira', 'full')
        expect(config).to have_key('issues_enabled')
        expect(config).to have_key('jira_auth_type')
        expect(config).to have_key('jira_issue_prefix')
        expect(config).to have_key('jira_issue_regex')
        expect(config).to have_key('jira_issue_transition_automatic')
        expect(config).to have_key('jira_issue_transition_id')
        expect(config).to have_key('project_key')
        expect(config).to have_key('project_keys')
        expect(config).to have_key('use_inherited_settings')
        expect(config).to have_key('username')
      end
    end

    context 'optional attributes' do
      it 'includes issues_enabled when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('opt', required_attrs.merge(issues_enabled: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'opt')
        expect(config).to have_key('issues_enabled')
      end

      it 'omits issues_enabled when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'minimal')
        expect(config).not_to have_key('issues_enabled')
      end
      it 'includes jira_auth_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('opt', required_attrs.merge(jira_auth_type: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'opt')
        expect(config).to have_key('jira_auth_type')
      end

      it 'omits jira_auth_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'minimal')
        expect(config).not_to have_key('jira_auth_type')
      end
      it 'includes jira_issue_prefix when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('opt', required_attrs.merge(jira_issue_prefix: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'opt')
        expect(config).to have_key('jira_issue_prefix')
      end

      it 'omits jira_issue_prefix when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'minimal')
        expect(config).not_to have_key('jira_issue_prefix')
      end
      it 'includes jira_issue_regex when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('opt', required_attrs.merge(jira_issue_regex: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'opt')
        expect(config).to have_key('jira_issue_regex')
      end

      it 'omits jira_issue_regex when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'minimal')
        expect(config).not_to have_key('jira_issue_regex')
      end
      it 'includes jira_issue_transition_automatic when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('opt', required_attrs.merge(jira_issue_transition_automatic: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'opt')
        expect(config).to have_key('jira_issue_transition_automatic')
      end

      it 'omits jira_issue_transition_automatic when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'minimal')
        expect(config).not_to have_key('jira_issue_transition_automatic')
      end
      it 'includes jira_issue_transition_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('opt', required_attrs.merge(jira_issue_transition_id: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'opt')
        expect(config).to have_key('jira_issue_transition_id')
      end

      it 'omits jira_issue_transition_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'minimal')
        expect(config).not_to have_key('jira_issue_transition_id')
      end
      it 'includes project_key when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('opt', required_attrs.merge(project_key: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'opt')
        expect(config).to have_key('project_key')
      end

      it 'omits project_key when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'minimal')
        expect(config).not_to have_key('project_key')
      end
      it 'includes project_keys when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('opt', required_attrs.merge(project_keys: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'opt')
        expect(config).to have_key('project_keys')
      end

      it 'omits project_keys when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'minimal')
        expect(config).not_to have_key('project_keys')
      end
      it 'includes use_inherited_settings when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('opt', required_attrs.merge(use_inherited_settings: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'opt')
        expect(config).to have_key('use_inherited_settings')
      end

      it 'omits use_inherited_settings when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'minimal')
        expect(config).not_to have_key('use_inherited_settings')
      end
      it 'includes username when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('opt', required_attrs.merge(username: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'opt')
        expect(config).to have_key('username')
      end

      it 'omits username when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_service_jira', 'minimal')
        expect(config).not_to have_key('username')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:password]
        expect(sensitive_fields).to include(:password)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts issues_enabled=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(issues_enabled: val)
          synth.gitlab_service_jira("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_service_jira', "bool_#{val}")
          expect(config['issues_enabled']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts jira_issue_transition_automatic=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(jira_issue_transition_automatic: val)
          synth.gitlab_service_jira("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_service_jira', "bool_#{val}")
          expect(config['jira_issue_transition_automatic']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts use_inherited_settings=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(use_inherited_settings: val)
          synth.gitlab_service_jira("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_service_jira', "bool_#{val}")
          expect(config['use_inherited_settings']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_service_jira', 'typed')
        expect(config['password']).to be_a(String)
        expect(config['project']).to be_a(String)
        expect(config['url']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_service_jira('first', required_attrs)
        synth.gitlab_service_jira('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_service_jira')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_service_jira,
    method: :gitlab_service_jira,
    required_attrs: { password: 'test-value', project: 'test-value', url: 'test-value' },
    expected_outputs: [:id, :active, :api_url, :comment_on_event_enabled, :commit_events, :created_at, :merge_requests_events, :title, :updated_at],
    sensitive_fields: [:password],
    immutable_fields: [],
    boolean_fields: [:issues_enabled, :jira_issue_transition_automatic, :use_inherited_settings]
end
