# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_integration_pipelines_email resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabIntegrationPipelinesEmail do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project: 'test-value', recipients: ['test-value'] } }

  describe ':gitlab_integration_pipelines_email' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_pipelines_email('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_integration_pipelines_email', 'test')
        validate_required_attributes(config, [:project, :recipients])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_integration_pipelines_email('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_integration_pipelines_email)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_integration_pipelines_email('test', required_attrs)

        expect(ref.id).to eq("${gitlab_integration_pipelines_email.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ branches_to_be_notified: 'test-value', notify_only_broken_pipelines: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_pipelines_email('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_integration_pipelines_email', 'full')
        expect(config).to have_key('branches_to_be_notified')
        expect(config).to have_key('notify_only_broken_pipelines')
      end
    end

    context 'optional attributes' do
      it 'includes branches_to_be_notified when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_pipelines_email('opt', required_attrs.merge(branches_to_be_notified: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_pipelines_email', 'opt')
        expect(config).to have_key('branches_to_be_notified')
      end

      it 'omits branches_to_be_notified when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_pipelines_email('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_pipelines_email', 'minimal')
        expect(config).not_to have_key('branches_to_be_notified')
      end
      it 'includes notify_only_broken_pipelines when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_pipelines_email('opt', required_attrs.merge(notify_only_broken_pipelines: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_pipelines_email', 'opt')
        expect(config).to have_key('notify_only_broken_pipelines')
      end

      it 'omits notify_only_broken_pipelines when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_pipelines_email('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_integration_pipelines_email', 'minimal')
        expect(config).not_to have_key('notify_only_broken_pipelines')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts notify_only_broken_pipelines=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(notify_only_broken_pipelines: val)
          synth.gitlab_integration_pipelines_email("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_integration_pipelines_email', "bool_#{val}")
          expect(config['notify_only_broken_pipelines']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_pipelines_email('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_integration_pipelines_email', 'typed')
        expect(config['project']).to be_a(String)
        expect(config['recipients']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_integration_pipelines_email('first', required_attrs)
        synth.gitlab_integration_pipelines_email('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_integration_pipelines_email')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_integration_pipelines_email,
    method: :gitlab_integration_pipelines_email,
    required_attrs: { project: 'test-value', recipients: ['test-value'] },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:notify_only_broken_pipelines]
end
