# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_project_milestone resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabProjectMilestone do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project: 'test-value', title: 'test-value' } }

  describe ':gitlab_project_milestone' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_milestone('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_project_milestone', 'test')
        validate_required_attributes(config, [:project, :title])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_milestone('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_project_milestone)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_milestone('test', required_attrs)

        expect(ref.id).to eq("${gitlab_project_milestone.test.id}")
        expect(ref.created_at).to eq("${gitlab_project_milestone.test.created_at}")
        expect(ref.expired).to eq("${gitlab_project_milestone.test.expired}")
        expect(ref.iid).to eq("${gitlab_project_milestone.test.iid}")
        expect(ref.milestone_id).to eq("${gitlab_project_milestone.test.milestone_id}")
        expect(ref.project_id).to eq("${gitlab_project_milestone.test.project_id}")
        expect(ref.updated_at).to eq("${gitlab_project_milestone.test.updated_at}")
        expect(ref.web_url).to eq("${gitlab_project_milestone.test.web_url}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_milestone('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_milestone', 'test')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('expired')
        expect(config).not_to have_key('iid')
        expect(config).not_to have_key('milestone_id')
        expect(config).not_to have_key('project_id')
        expect(config).not_to have_key('updated_at')
        expect(config).not_to have_key('web_url')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ description: 'test-value', due_date: 'test-value', start_date: 'test-value', state: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_milestone('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_milestone', 'full')
        expect(config).to have_key('description')
        expect(config).to have_key('due_date')
        expect(config).to have_key('start_date')
        expect(config).to have_key('state')
      end
    end

    context 'optional attributes' do
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_milestone('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_milestone', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_milestone('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_milestone', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes due_date when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_milestone('opt', required_attrs.merge(due_date: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_milestone', 'opt')
        expect(config).to have_key('due_date')
      end

      it 'omits due_date when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_milestone('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_milestone', 'minimal')
        expect(config).not_to have_key('due_date')
      end
      it 'includes start_date when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_milestone('opt', required_attrs.merge(start_date: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_milestone', 'opt')
        expect(config).to have_key('start_date')
      end

      it 'omits start_date when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_milestone('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_milestone', 'minimal')
        expect(config).not_to have_key('start_date')
      end
      it 'includes state when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_milestone('opt', required_attrs.merge(state: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_milestone', 'opt')
        expect(config).to have_key('state')
      end

      it 'omits state when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_milestone('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_milestone', 'minimal')
        expect(config).not_to have_key('state')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_milestone('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_milestone', 'typed')
        expect(config['project']).to be_a(String)
        expect(config['title']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_milestone('first', required_attrs)
        synth.gitlab_project_milestone('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_project_milestone')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_project_milestone,
    method: :gitlab_project_milestone,
    required_attrs: { project: 'test-value', title: 'test-value' },
    expected_outputs: [:id, :created_at, :expired, :iid, :milestone_id, :project_id, :updated_at, :web_url],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
