# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_application resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabApplication do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', redirect_url: 'test-value', scopes: ['test-value'] } }

  describe ':gitlab_application' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_application('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_application', 'test')
        validate_required_attributes(config, [:name, :redirect_url, :scopes])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_application('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_application)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_application('test', required_attrs)

        expect(ref.id).to eq("${gitlab_application.test.id}")
        expect(ref.application_id).to eq("${gitlab_application.test.application_id}")
        expect(ref.confidential).to eq("${gitlab_application.test.confidential}")
        expect(ref.secret).to eq("${gitlab_application.test.secret}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_application('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_application', 'test')
        expect(config).not_to have_key('application_id')
        expect(config).not_to have_key('confidential')
        expect(config).not_to have_key('secret')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:secret]
        expect(sensitive_fields).to include(:secret)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_application('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_application', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['redirect_url']).to be_a(String)
        expect(config['scopes']).to be_a(Array)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_application('first', required_attrs)
        synth.gitlab_application('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_application')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_application,
    method: :gitlab_application,
    required_attrs: { name: 'test-value', redirect_url: 'test-value', scopes: ['test-value'] },
    expected_outputs: [:id, :application_id, :confidential, :secret],
    sensitive_fields: [:secret],
    immutable_fields: [],
    boolean_fields: []
end
