# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_project_job_token_scopes resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabProjectJobTokenScopes do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { {} }

  describe ':gitlab_project_job_token_scopes' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_job_token_scopes('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_project_job_token_scopes', 'test')
        validate_required_attributes(config, [])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_job_token_scopes('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_project_job_token_scopes)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_job_token_scopes('test', required_attrs)

        expect(ref.id).to eq("${gitlab_project_job_token_scopes.test.id}")
        expect(ref.enabled).to eq("${gitlab_project_job_token_scopes.test.enabled}")
        expect(ref.project).to eq("${gitlab_project_job_token_scopes.test.project}")
        expect(ref.project_id).to eq("${gitlab_project_job_token_scopes.test.project_id}")
        expect(ref.target_group_ids).to eq("${gitlab_project_job_token_scopes.test.target_group_ids}")
        expect(ref.target_project_ids).to eq("${gitlab_project_job_token_scopes.test.target_project_ids}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_job_token_scopes('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_job_token_scopes', 'test')
        expect(config).not_to have_key('enabled')
        expect(config).not_to have_key('project')
        expect(config).not_to have_key('project_id')
        expect(config).not_to have_key('target_group_ids')
        expect(config).not_to have_key('target_project_ids')
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_job_token_scopes('first', required_attrs)
        synth.gitlab_project_job_token_scopes('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_project_job_token_scopes')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_project_job_token_scopes,
    method: :gitlab_project_job_token_scopes,
    required_attrs: {},
    expected_outputs: [:id, :enabled, :project, :project_id, :target_group_ids, :target_project_ids],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
