# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_personal_access_token resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabPersonalAccessToken do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', scopes: ['test-value'], user_id: 3.14 } }

  describe ':gitlab_personal_access_token' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_personal_access_token('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_personal_access_token', 'test')
        validate_required_attributes(config, [:name, :scopes, :user_id])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_personal_access_token('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_personal_access_token)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_personal_access_token('test', required_attrs)

        expect(ref.id).to eq("${gitlab_personal_access_token.test.id}")
        expect(ref.active).to eq("${gitlab_personal_access_token.test.active}")
        expect(ref.created_at).to eq("${gitlab_personal_access_token.test.created_at}")
        expect(ref.description).to eq("${gitlab_personal_access_token.test.description}")
        expect(ref.expires_at).to eq("${gitlab_personal_access_token.test.expires_at}")
        expect(ref.revoked).to eq("${gitlab_personal_access_token.test.revoked}")
        expect(ref.token).to eq("${gitlab_personal_access_token.test.token}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_personal_access_token('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_personal_access_token', 'test')
        expect(config).not_to have_key('active')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('description')
        expect(config).not_to have_key('expires_at')
        expect(config).not_to have_key('revoked')
        expect(config).not_to have_key('token')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ rotation_configuration: { 'key1' => 'val1' } }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_personal_access_token('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_personal_access_token', 'full')
        expect(config).to have_key('rotation_configuration')
      end
    end

    context 'optional attributes' do
      it 'includes rotation_configuration when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_personal_access_token('opt', required_attrs.merge(rotation_configuration: { 'key1' => 'val1' }))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_personal_access_token', 'opt')
        expect(config).to have_key('rotation_configuration')
      end

      it 'omits rotation_configuration when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_personal_access_token('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_personal_access_token', 'minimal')
        expect(config).not_to have_key('rotation_configuration')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:token]
        expect(sensitive_fields).to include(:token)
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_personal_access_token('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_personal_access_token', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['scopes']).to be_a(Array)
        expect(config['user_id']).to be_a(Float)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_personal_access_token('first', required_attrs)
        synth.gitlab_personal_access_token('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_personal_access_token')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_personal_access_token,
    method: :gitlab_personal_access_token,
    required_attrs: { name: 'test-value', scopes: ['test-value'], user_id: 3.14 },
    expected_outputs: [:id, :active, :created_at, :description, :expires_at, :revoked, :token],
    sensitive_fields: [:token],
    immutable_fields: [],
    boolean_fields: []
end
