# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_tag_protection resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabTagProtection do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project: 'test-value', tag: 'test-value' } }

  describe ':gitlab_tag_protection' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_tag_protection('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_tag_protection', 'test')
        validate_required_attributes(config, [:project, :tag])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_tag_protection('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_tag_protection)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_tag_protection('test', required_attrs)

        expect(ref.id).to eq("${gitlab_tag_protection.test.id}")
        expect(ref.create_access_level).to eq("${gitlab_tag_protection.test.create_access_level}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_tag_protection('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_tag_protection', 'test')
        expect(config).not_to have_key('create_access_level')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ allowed_to_create: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_tag_protection('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_tag_protection', 'full')
        expect(config).to have_key('allowed_to_create')
      end
    end

    context 'optional attributes' do
      it 'includes allowed_to_create when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_tag_protection('opt', required_attrs.merge(allowed_to_create: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_tag_protection', 'opt')
        expect(config).to have_key('allowed_to_create')
      end

      it 'omits allowed_to_create when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_tag_protection('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_tag_protection', 'minimal')
        expect(config).not_to have_key('allowed_to_create')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_tag_protection('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_tag_protection', 'typed')
        expect(config['project']).to be_a(String)
        expect(config['tag']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_tag_protection('first', required_attrs)
        synth.gitlab_tag_protection('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_tag_protection')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_tag_protection,
    method: :gitlab_tag_protection,
    required_attrs: { project: 'test-value', tag: 'test-value' },
    expected_outputs: [:id, :create_access_level],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
