# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_project_issue resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabProjectIssue do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { project: 'test-value', title: 'test-value' } }

  describe ':gitlab_project_issue' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'test')
        validate_required_attributes(config, [:project, :title])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_issue('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_project_issue)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_issue('test', required_attrs)

        expect(ref.id).to eq("${gitlab_project_issue.test.id}")
        expect(ref.author_id).to eq("${gitlab_project_issue.test.author_id}")
        expect(ref.closed_at).to eq("${gitlab_project_issue.test.closed_at}")
        expect(ref.closed_by_user_id).to eq("${gitlab_project_issue.test.closed_by_user_id}")
        expect(ref.created_at).to eq("${gitlab_project_issue.test.created_at}")
        expect(ref.downvotes).to eq("${gitlab_project_issue.test.downvotes}")
        expect(ref.epic_id).to eq("${gitlab_project_issue.test.epic_id}")
        expect(ref.epic_issue_id).to eq("${gitlab_project_issue.test.epic_issue_id}")
        expect(ref.external_id).to eq("${gitlab_project_issue.test.external_id}")
        expect(ref.human_time_estimate).to eq("${gitlab_project_issue.test.human_time_estimate}")
        expect(ref.human_total_time_spent).to eq("${gitlab_project_issue.test.human_total_time_spent}")
        expect(ref.iid).to eq("${gitlab_project_issue.test.iid}")
        expect(ref.issue_id).to eq("${gitlab_project_issue.test.issue_id}")
        expect(ref.issue_link_id).to eq("${gitlab_project_issue.test.issue_link_id}")
        expect(ref.links).to eq("${gitlab_project_issue.test.links}")
        expect(ref.merge_requests_count).to eq("${gitlab_project_issue.test.merge_requests_count}")
        expect(ref.moved_to_id).to eq("${gitlab_project_issue.test.moved_to_id}")
        expect(ref.references).to eq("${gitlab_project_issue.test.references}")
        expect(ref.subscribed).to eq("${gitlab_project_issue.test.subscribed}")
        expect(ref.task_completion_status).to eq("${gitlab_project_issue.test.task_completion_status}")
        expect(ref.time_estimate).to eq("${gitlab_project_issue.test.time_estimate}")
        expect(ref.total_time_spent).to eq("${gitlab_project_issue.test.total_time_spent}")
        expect(ref.updated_at).to eq("${gitlab_project_issue.test.updated_at}")
        expect(ref.upvotes).to eq("${gitlab_project_issue.test.upvotes}")
        expect(ref.user_notes_count).to eq("${gitlab_project_issue.test.user_notes_count}")
        expect(ref.web_url).to eq("${gitlab_project_issue.test.web_url}")
        expect(ref.weight).to eq("${gitlab_project_issue.test.weight}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_issue', 'test')
        expect(config).not_to have_key('author_id')
        expect(config).not_to have_key('closed_at')
        expect(config).not_to have_key('closed_by_user_id')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('downvotes')
        expect(config).not_to have_key('epic_id')
        expect(config).not_to have_key('epic_issue_id')
        expect(config).not_to have_key('external_id')
        expect(config).not_to have_key('human_time_estimate')
        expect(config).not_to have_key('human_total_time_spent')
        expect(config).not_to have_key('iid')
        expect(config).not_to have_key('issue_id')
        expect(config).not_to have_key('issue_link_id')
        expect(config).not_to have_key('links')
        expect(config).not_to have_key('merge_requests_count')
        expect(config).not_to have_key('moved_to_id')
        expect(config).not_to have_key('references')
        expect(config).not_to have_key('subscribed')
        expect(config).not_to have_key('task_completion_status')
        expect(config).not_to have_key('time_estimate')
        expect(config).not_to have_key('total_time_spent')
        expect(config).not_to have_key('updated_at')
        expect(config).not_to have_key('upvotes')
        expect(config).not_to have_key('user_notes_count')
        expect(config).not_to have_key('web_url')
        expect(config).not_to have_key('weight')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ assignee_ids: [3.14], confidential: true, delete_on_destroy: true, description: 'test-value', discussion_locked: true, discussion_to_resolve: 'test-value', due_date: 'test-value', issue_type: 'test-value', labels: ['test-value'], merge_request_to_resolve_discussions_of: 3.14, milestone_id: 3.14, state: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_issue', 'full')
        expect(config).to have_key('assignee_ids')
        expect(config).to have_key('confidential')
        expect(config).to have_key('delete_on_destroy')
        expect(config).to have_key('description')
        expect(config).to have_key('discussion_locked')
        expect(config).to have_key('discussion_to_resolve')
        expect(config).to have_key('due_date')
        expect(config).to have_key('issue_type')
        expect(config).to have_key('labels')
        expect(config).to have_key('merge_request_to_resolve_discussions_of')
        expect(config).to have_key('milestone_id')
        expect(config).to have_key('state')
      end
    end

    context 'optional attributes' do
      it 'includes assignee_ids when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('opt', required_attrs.merge(assignee_ids: [3.14]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'opt')
        expect(config).to have_key('assignee_ids')
      end

      it 'omits assignee_ids when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'minimal')
        expect(config).not_to have_key('assignee_ids')
      end
      it 'includes confidential when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('opt', required_attrs.merge(confidential: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'opt')
        expect(config).to have_key('confidential')
      end

      it 'omits confidential when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'minimal')
        expect(config).not_to have_key('confidential')
      end
      it 'includes delete_on_destroy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('opt', required_attrs.merge(delete_on_destroy: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'opt')
        expect(config).to have_key('delete_on_destroy')
      end

      it 'omits delete_on_destroy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'minimal')
        expect(config).not_to have_key('delete_on_destroy')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes discussion_locked when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('opt', required_attrs.merge(discussion_locked: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'opt')
        expect(config).to have_key('discussion_locked')
      end

      it 'omits discussion_locked when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'minimal')
        expect(config).not_to have_key('discussion_locked')
      end
      it 'includes discussion_to_resolve when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('opt', required_attrs.merge(discussion_to_resolve: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'opt')
        expect(config).to have_key('discussion_to_resolve')
      end

      it 'omits discussion_to_resolve when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'minimal')
        expect(config).not_to have_key('discussion_to_resolve')
      end
      it 'includes due_date when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('opt', required_attrs.merge(due_date: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'opt')
        expect(config).to have_key('due_date')
      end

      it 'omits due_date when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'minimal')
        expect(config).not_to have_key('due_date')
      end
      it 'includes issue_type when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('opt', required_attrs.merge(issue_type: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'opt')
        expect(config).to have_key('issue_type')
      end

      it 'omits issue_type when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'minimal')
        expect(config).not_to have_key('issue_type')
      end
      it 'includes labels when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('opt', required_attrs.merge(labels: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'opt')
        expect(config).to have_key('labels')
      end

      it 'omits labels when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'minimal')
        expect(config).not_to have_key('labels')
      end
      it 'includes merge_request_to_resolve_discussions_of when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('opt', required_attrs.merge(merge_request_to_resolve_discussions_of: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'opt')
        expect(config).to have_key('merge_request_to_resolve_discussions_of')
      end

      it 'omits merge_request_to_resolve_discussions_of when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'minimal')
        expect(config).not_to have_key('merge_request_to_resolve_discussions_of')
      end
      it 'includes milestone_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('opt', required_attrs.merge(milestone_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'opt')
        expect(config).to have_key('milestone_id')
      end

      it 'omits milestone_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'minimal')
        expect(config).not_to have_key('milestone_id')
      end
      it 'includes state when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('opt', required_attrs.merge(state: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'opt')
        expect(config).to have_key('state')
      end

      it 'omits state when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_issue', 'minimal')
        expect(config).not_to have_key('state')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts confidential=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(confidential: val)
          synth.gitlab_project_issue("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_project_issue', "bool_#{val}")
          expect(config['confidential']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts delete_on_destroy=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(delete_on_destroy: val)
          synth.gitlab_project_issue("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_project_issue', "bool_#{val}")
          expect(config['delete_on_destroy']).to eq(val)
        end
      end
      [true, false].each do |val|
        it "accepts discussion_locked=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(discussion_locked: val)
          synth.gitlab_project_issue("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_project_issue', "bool_#{val}")
          expect(config['discussion_locked']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_issue', 'typed')
        expect(config['project']).to be_a(String)
        expect(config['title']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_issue('first', required_attrs)
        synth.gitlab_project_issue('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_project_issue')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_project_issue,
    method: :gitlab_project_issue,
    required_attrs: { project: 'test-value', title: 'test-value' },
    expected_outputs: [:id, :author_id, :closed_at, :closed_by_user_id, :created_at, :downvotes, :epic_id, :epic_issue_id, :external_id, :human_time_estimate, :human_total_time_spent, :iid, :issue_id, :issue_link_id, :links, :merge_requests_count, :moved_to_id, :references, :subscribed, :task_completion_status, :time_estimate, :total_time_spent, :updated_at, :upvotes, :user_notes_count, :web_url, :weight],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:confidential, :delete_on_destroy, :discussion_locked]
end
