# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_group resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabGroup do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', path: 'test-value' } }

  describe ':gitlab_group' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_group', 'test')
        validate_required_attributes(config, [:name, :path])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_group('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_group)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_group('test', required_attrs)

        expect(ref.id).to eq("${gitlab_group.test.id}")
        expect(ref.allowed_email_domains_list).to eq("${gitlab_group.test.allowed_email_domains_list}")
        expect(ref.auto_devops_enabled).to eq("${gitlab_group.test.auto_devops_enabled}")
        expect(ref.avatar_hash).to eq("${gitlab_group.test.avatar_hash}")
        expect(ref.avatar_url).to eq("${gitlab_group.test.avatar_url}")
        expect(ref.default_branch_protection).to eq("${gitlab_group.test.default_branch_protection}")
        expect(ref.emails_enabled).to eq("${gitlab_group.test.emails_enabled}")
        expect(ref.extra_shared_runners_minutes_limit).to eq("${gitlab_group.test.extra_shared_runners_minutes_limit}")
        expect(ref.full_name).to eq("${gitlab_group.test.full_name}")
        expect(ref.full_path).to eq("${gitlab_group.test.full_path}")
        expect(ref.lfs_enabled).to eq("${gitlab_group.test.lfs_enabled}")
        expect(ref.membership_lock).to eq("${gitlab_group.test.membership_lock}")
        expect(ref.mentions_disabled).to eq("${gitlab_group.test.mentions_disabled}")
        expect(ref.parent_id).to eq("${gitlab_group.test.parent_id}")
        expect(ref.prevent_forking_outside_group).to eq("${gitlab_group.test.prevent_forking_outside_group}")
        expect(ref.project_creation_level).to eq("${gitlab_group.test.project_creation_level}")
        expect(ref.request_access_enabled).to eq("${gitlab_group.test.request_access_enabled}")
        expect(ref.require_two_factor_authentication).to eq("${gitlab_group.test.require_two_factor_authentication}")
        expect(ref.runners_token).to eq("${gitlab_group.test.runners_token}")
        expect(ref.share_with_group_lock).to eq("${gitlab_group.test.share_with_group_lock}")
        expect(ref.shared_runners_minutes_limit).to eq("${gitlab_group.test.shared_runners_minutes_limit}")
        expect(ref.shared_runners_setting).to eq("${gitlab_group.test.shared_runners_setting}")
        expect(ref.subgroup_creation_level).to eq("${gitlab_group.test.subgroup_creation_level}")
        expect(ref.two_factor_grace_period).to eq("${gitlab_group.test.two_factor_grace_period}")
        expect(ref.visibility_level).to eq("${gitlab_group.test.visibility_level}")
        expect(ref.web_url).to eq("${gitlab_group.test.web_url}")
        expect(ref.wiki_access_level).to eq("${gitlab_group.test.wiki_access_level}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_group', 'test')
        expect(config).not_to have_key('allowed_email_domains_list')
        expect(config).not_to have_key('auto_devops_enabled')
        expect(config).not_to have_key('avatar_hash')
        expect(config).not_to have_key('avatar_url')
        expect(config).not_to have_key('default_branch_protection')
        expect(config).not_to have_key('emails_enabled')
        expect(config).not_to have_key('extra_shared_runners_minutes_limit')
        expect(config).not_to have_key('full_name')
        expect(config).not_to have_key('full_path')
        expect(config).not_to have_key('lfs_enabled')
        expect(config).not_to have_key('membership_lock')
        expect(config).not_to have_key('mentions_disabled')
        expect(config).not_to have_key('parent_id')
        expect(config).not_to have_key('prevent_forking_outside_group')
        expect(config).not_to have_key('project_creation_level')
        expect(config).not_to have_key('request_access_enabled')
        expect(config).not_to have_key('require_two_factor_authentication')
        expect(config).not_to have_key('runners_token')
        expect(config).not_to have_key('share_with_group_lock')
        expect(config).not_to have_key('shared_runners_minutes_limit')
        expect(config).not_to have_key('shared_runners_setting')
        expect(config).not_to have_key('subgroup_creation_level')
        expect(config).not_to have_key('two_factor_grace_period')
        expect(config).not_to have_key('visibility_level')
        expect(config).not_to have_key('web_url')
        expect(config).not_to have_key('wiki_access_level')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ avatar: 'test-value', default_branch: 'test-value', default_branch_protection_defaults: [{ 'key1' => 'val1' }], description: 'test-value', ip_restriction_ranges: ['test-value'], permanently_remove_on_delete: true, push_rules: [{ 'key1' => 'val1' }] }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_group', 'full')
        expect(config).to have_key('avatar')
        expect(config).to have_key('default_branch')
        expect(config).to have_key('default_branch_protection_defaults')
        expect(config).to have_key('description')
        expect(config).to have_key('ip_restriction_ranges')
        expect(config).to have_key('permanently_remove_on_delete')
        expect(config).to have_key('push_rules')
      end
    end

    context 'optional attributes' do
      it 'includes avatar when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('opt', required_attrs.merge(avatar: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group', 'opt')
        expect(config).to have_key('avatar')
      end

      it 'omits avatar when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group', 'minimal')
        expect(config).not_to have_key('avatar')
      end
      it 'includes default_branch when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('opt', required_attrs.merge(default_branch: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group', 'opt')
        expect(config).to have_key('default_branch')
      end

      it 'omits default_branch when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group', 'minimal')
        expect(config).not_to have_key('default_branch')
      end
      it 'includes default_branch_protection_defaults when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('opt', required_attrs.merge(default_branch_protection_defaults: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group', 'opt')
        expect(config).to have_key('default_branch_protection_defaults')
      end

      it 'omits default_branch_protection_defaults when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group', 'minimal')
        expect(config).not_to have_key('default_branch_protection_defaults')
      end
      it 'includes description when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('opt', required_attrs.merge(description: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group', 'opt')
        expect(config).to have_key('description')
      end

      it 'omits description when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group', 'minimal')
        expect(config).not_to have_key('description')
      end
      it 'includes ip_restriction_ranges when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('opt', required_attrs.merge(ip_restriction_ranges: ['test-value']))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group', 'opt')
        expect(config).to have_key('ip_restriction_ranges')
      end

      it 'omits ip_restriction_ranges when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group', 'minimal')
        expect(config).not_to have_key('ip_restriction_ranges')
      end
      it 'includes permanently_remove_on_delete when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('opt', required_attrs.merge(permanently_remove_on_delete: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group', 'opt')
        expect(config).to have_key('permanently_remove_on_delete')
      end

      it 'omits permanently_remove_on_delete when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group', 'minimal')
        expect(config).not_to have_key('permanently_remove_on_delete')
      end
      it 'includes push_rules when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('opt', required_attrs.merge(push_rules: [{ 'key1' => 'val1' }]))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group', 'opt')
        expect(config).to have_key('push_rules')
      end

      it 'omits push_rules when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_group', 'minimal')
        expect(config).not_to have_key('push_rules')
      end
    end

    context 'sensitive fields' do
      it 'documents sensitive attributes' do
        sensitive_fields = [:runners_token]
        expect(sensitive_fields).to include(:runners_token)
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts permanently_remove_on_delete=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(permanently_remove_on_delete: val)
          synth.gitlab_group("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_group', "bool_#{val}")
          expect(config['permanently_remove_on_delete']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_group', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['path']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_group('first', required_attrs)
        synth.gitlab_group('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_group')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_group,
    method: :gitlab_group,
    required_attrs: { name: 'test-value', path: 'test-value' },
    expected_outputs: [:id, :allowed_email_domains_list, :auto_devops_enabled, :avatar_hash, :avatar_url, :default_branch_protection, :emails_enabled, :extra_shared_runners_minutes_limit, :full_name, :full_path, :lfs_enabled, :membership_lock, :mentions_disabled, :parent_id, :prevent_forking_outside_group, :project_creation_level, :request_access_enabled, :require_two_factor_authentication, :runners_token, :share_with_group_lock, :shared_runners_minutes_limit, :shared_runners_setting, :subgroup_creation_level, :two_factor_grace_period, :visibility_level, :web_url, :wiki_access_level],
    sensitive_fields: [:runners_token],
    immutable_fields: [],
    boolean_fields: [:permanently_remove_on_delete]
end
