# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_project_environment resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabProjectEnvironment do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { name: 'test-value', project: 'test-value' } }

  describe ':gitlab_project_environment' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_environment('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_project_environment', 'test')
        validate_required_attributes(config, [:name, :project])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_environment('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_project_environment)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_environment('test', required_attrs)

        expect(ref.id).to eq("${gitlab_project_environment.test.id}")
        expect(ref.auto_stop_at).to eq("${gitlab_project_environment.test.auto_stop_at}")
        expect(ref.auto_stop_setting).to eq("${gitlab_project_environment.test.auto_stop_setting}")
        expect(ref.created_at).to eq("${gitlab_project_environment.test.created_at}")
        expect(ref.description).to eq("${gitlab_project_environment.test.description}")
        expect(ref.slug).to eq("${gitlab_project_environment.test.slug}")
        expect(ref.state).to eq("${gitlab_project_environment.test.state}")
        expect(ref.tier).to eq("${gitlab_project_environment.test.tier}")
        expect(ref.updated_at).to eq("${gitlab_project_environment.test.updated_at}")
      end
    end

    context 'computed-only attributes' do
      it 'excludes computed-only attributes from the resource block' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_environment('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_environment', 'test')
        expect(config).not_to have_key('auto_stop_at')
        expect(config).not_to have_key('auto_stop_setting')
        expect(config).not_to have_key('created_at')
        expect(config).not_to have_key('description')
        expect(config).not_to have_key('slug')
        expect(config).not_to have_key('state')
        expect(config).not_to have_key('tier')
        expect(config).not_to have_key('updated_at')
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ cluster_agent_id: 3.14, external_url: 'test-value', flux_resource_path: 'test-value', kubernetes_namespace: 'test-value', stop_before_destroy: true }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_environment('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_environment', 'full')
        expect(config).to have_key('cluster_agent_id')
        expect(config).to have_key('external_url')
        expect(config).to have_key('flux_resource_path')
        expect(config).to have_key('kubernetes_namespace')
        expect(config).to have_key('stop_before_destroy')
      end
    end

    context 'optional attributes' do
      it 'includes cluster_agent_id when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_environment('opt', required_attrs.merge(cluster_agent_id: 3.14))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_environment', 'opt')
        expect(config).to have_key('cluster_agent_id')
      end

      it 'omits cluster_agent_id when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_environment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_environment', 'minimal')
        expect(config).not_to have_key('cluster_agent_id')
      end
      it 'includes external_url when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_environment('opt', required_attrs.merge(external_url: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_environment', 'opt')
        expect(config).to have_key('external_url')
      end

      it 'omits external_url when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_environment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_environment', 'minimal')
        expect(config).not_to have_key('external_url')
      end
      it 'includes flux_resource_path when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_environment('opt', required_attrs.merge(flux_resource_path: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_environment', 'opt')
        expect(config).to have_key('flux_resource_path')
      end

      it 'omits flux_resource_path when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_environment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_environment', 'minimal')
        expect(config).not_to have_key('flux_resource_path')
      end
      it 'includes kubernetes_namespace when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_environment('opt', required_attrs.merge(kubernetes_namespace: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_environment', 'opt')
        expect(config).to have_key('kubernetes_namespace')
      end

      it 'omits kubernetes_namespace when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_environment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_environment', 'minimal')
        expect(config).not_to have_key('kubernetes_namespace')
      end
      it 'includes stop_before_destroy when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_environment('opt', required_attrs.merge(stop_before_destroy: true))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_environment', 'opt')
        expect(config).to have_key('stop_before_destroy')
      end

      it 'omits stop_before_destroy when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_environment('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_environment', 'minimal')
        expect(config).not_to have_key('stop_before_destroy')
      end
    end

    context 'boolean fields' do
      [true, false].each do |val|
        it "accepts stop_before_destroy=#{val}" do
          synth = create_synthesizer
          synth.extend(described_class)
          attrs = required_attrs.merge(stop_before_destroy: val)
          synth.gitlab_project_environment("bool_#{val}", attrs)
          result = normalize_synthesis(synth.synthesis)
          config = validate_resource_structure(result, 'gitlab_project_environment', "bool_#{val}")
          expect(config['stop_before_destroy']).to eq(val)
        end
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_environment('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_environment', 'typed')
        expect(config['name']).to be_a(String)
        expect(config['project']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_environment('first', required_attrs)
        synth.gitlab_project_environment('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_project_environment')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_project_environment,
    method: :gitlab_project_environment,
    required_attrs: { name: 'test-value', project: 'test-value' },
    expected_outputs: [:id, :auto_stop_at, :auto_stop_setting, :created_at, :description, :slug, :state, :tier, :updated_at],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: [:stop_before_destroy]
end
