# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.
# Resource: Manages a gitlab_project_share_group resource
# Source: terraform-apply

require 'spec_helper'

RSpec.describe Pangea::Resources::GitlabProjectShareGroup do
  include Pangea::Testing::SynthesisTestHelpers

  let(:required_attrs) { { group_id: 3.14, project: 'test-value' } }

  describe ':gitlab_project_share_group' do
    context 'with required attributes only' do
      it 'synthesizes valid Terraform JSON' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_share_group('test', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        validate_terraform_structure(result, :resource)
        config = validate_resource_structure(result, 'gitlab_project_share_group', 'test')
        validate_required_attributes(config, [:group_id, :project])
      end

      it 'returns a ResourceReference' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_share_group('test', required_attrs)

        expect(ref).to be_a(Pangea::Resources::ResourceReference)
        expect(ref.resource_type).to eq(:gitlab_project_share_group)
      end

      it 'provides output references' do
        synth = create_synthesizer
        synth.extend(described_class)
        ref = synth.gitlab_project_share_group('test', required_attrs)

        expect(ref.id).to eq("${gitlab_project_share_group.test.id}")
      end
    end

    context 'with all attributes' do
      let(:all_attrs) { required_attrs.merge({ access_level: 'test-value', group_access: 'test-value' }) }

      it 'synthesizes with optional attributes' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_share_group('full', all_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_share_group', 'full')
        expect(config).to have_key('access_level')
        expect(config).to have_key('group_access')
      end
    end

    context 'optional attributes' do
      it 'includes access_level when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_share_group('opt', required_attrs.merge(access_level: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_share_group', 'opt')
        expect(config).to have_key('access_level')
      end

      it 'omits access_level when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_share_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_share_group', 'minimal')
        expect(config).not_to have_key('access_level')
      end
      it 'includes group_access when provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_share_group('opt', required_attrs.merge(group_access: 'test-value'))
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_share_group', 'opt')
        expect(config).to have_key('group_access')
      end

      it 'omits group_access when not provided' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_share_group('minimal', required_attrs)
        result = normalize_synthesis(synth.synthesis)
        config = validate_resource_structure(result, 'gitlab_project_share_group', 'minimal')
        expect(config).not_to have_key('group_access')
      end
    end

    context 'attribute types' do
      it 'validates expected attribute types' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_share_group('typed', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        config = validate_resource_structure(result, 'gitlab_project_share_group', 'typed')
        expect(config['group_id']).to be_a(Float)
        expect(config['project']).to be_a(String)
      end
    end

    context 'multiple instances' do
      it 'synthesizes multiple resources independently' do
        synth = create_synthesizer
        synth.extend(described_class)
        synth.gitlab_project_share_group('first', required_attrs)
        synth.gitlab_project_share_group('second', required_attrs)
        result = normalize_synthesis(synth.synthesis)

        resources = result.dig('resource', 'gitlab_project_share_group')
        expect(resources.keys).to contain_exactly('first', 'second')
      end
    end

    context 'CRUD mapping' do
      it 'documents the API endpoints used' do
        # Create: terraform-apply
        # Read:   terraform-refresh
        # Update: terraform-apply
        # Delete: terraform-destroy
        expect('terraform-apply').not_to be_empty
        expect('terraform-refresh').not_to be_empty
        expect('terraform-destroy').not_to be_empty
      end
    end
  end

  it_behaves_like 'a generated pangea resource',
    resource_type: :gitlab_project_share_group,
    method: :gitlab_project_share_group,
    required_attrs: { group_id: 3.14, project: 'test-value' },
    expected_outputs: [:id],
    sensitive_fields: [],
    immutable_fields: [],
    boolean_fields: []
end
