# frozen_string_literal: true
# Code generated by pangea-forge. DO NOT EDIT.

require 'pangea/resources/base'
require 'pangea/resources/reference'
require 'pangea/resources/gitlab_project_variable/types'
require 'pangea/resource_registry'

module Pangea::Resources
  module GitlabProjectVariable
    include Pangea::Resources::ResourceBuilder

    define_resource :gitlab_project_variable,
      attributes_class: Gitlab::Types::ProjectVariableAttributes,
      outputs: { id: :id },
      map: [:key, :project, :value]
  end
  module Gitlab
    include GitlabProjectVariable
  end
end
Pangea::ResourceRegistry.register_module(Pangea::Resources::Gitlab)
